equinor/ecalc

.github/workflows/publish.yml

Enables pushing the package to pypi

ci: enable publish to pypi

---

README.md
pyproject.toml

outdated description replaced with new and better

chore: update description etc in readme

---

src/ecalc/libraries/libecalc/common/libecalc/core/models/compressor/train/utils/numeric_methods.py

This pull request is needed because the old docstring mentioned wrong algorithm. We use brenth not a pure brent method

chore: update docstring for numeric_methods

---

src/ecalc/libraries/libecalc/common/libecalc/core/consumers/compressor/component.py
src/ecalc/libraries/libecalc/common/libecalc/core/consumers/consumer_system.py
src/ecalc/libraries/libecalc/common/libecalc/core/consumers/pump/component.py
src/ecalc/libraries/libecalc/common/libecalc/core/result/results.py
src/ecalc/libraries/libecalc/common/libecalc/dto/core_specs/base/operational_settings.py
src/ecalc/libraries/libecalc/common/libecalc/dto/core_specs/compressor/operational_settings.py
src/ecalc/libraries/libecalc/common/libecalc/dto/core_specs/pump/operational_settings.py
src/ecalc/libraries/libecalc/common/tests/integration/snapshots/test_consumer_system_v2/test_compressor_system_v2_results/consumer_system_v2.json
src/ecalc/libraries/libecalc/common/tests/integration/test_consumer_system_v2.py

Adding detailed results to the new Consumer System V2

Add consumer system v2 sub results

---

pyproject.toml
src/ecalc/libraries/libecalc/common/libecalc/common/list_utils.py
src/ecalc/libraries/libecalc/common/libecalc/common/time_utils.py
src/ecalc/libraries/libecalc/common/libecalc/common/units.py
src/ecalc/libraries/libecalc/common/libecalc/common/utils/rates.py
src/ecalc/libraries/libecalc/common/libecalc/core/consumers/legacy_consumer/consumer_function/results.py
src/ecalc/libraries/libecalc/common/libecalc/core/consumers/legacy_consumer/system/consumer_function.py
src/ecalc/libraries/libecalc/common/libecalc/core/consumers/legacy_consumer/system/operational_setting.py
src/ecalc/libraries/libecalc/common/libecalc/core/consumers/legacy_consumer/system/results.py
src/ecalc/libraries/libecalc/common/libecalc/core/models/compressor/base.py
src/ecalc/libraries/libecalc/common/libecalc/core/models/compressor/sampled/compressor_model_sampled_3d.py
src/ecalc/libraries/libecalc/common/libecalc/core/models/compressor/train/stage.py
src/ecalc/libraries/libecalc/common/libecalc/core/models/compressor/train/utils/common.py
src/ecalc/libraries/libecalc/common/libecalc/core/models/compressor/train/utils/numeric_methods.py
src/ecalc/libraries/libecalc/common/libecalc/core/models/turbine.py
src/ecalc/libraries/libecalc/common/libecalc/input/file_io.py

On our road to mypy ´strict´ mode
- Turn on a few more mypy rules, fixes some errors

refactor: fix more typing

---

pyproject.toml
src/ecalc/libraries/libecalc/common/libecalc/common/time_utils.py
src/ecalc/libraries/libecalc/common/libecalc/common/units.py
src/ecalc/libraries/libecalc/common/libecalc/core/consumers/legacy_consumer/consumer_function_mapper/__init__.py
src/ecalc/libraries/libecalc/common/libecalc/core/models/compressor/factory.py
src/ecalc/libraries/libecalc/common/libecalc/core/models/pump/factory.py
src/ecalc/libraries/libecalc/common/libecalc/expression/expression_evaluator.py
src/ecalc/libraries/libecalc/common/libecalc/input/file_io.py
src/ecalc/libraries/libecalc/common/libecalc/input/mappers/component_mapper.py
src/ecalc/libraries/libecalc/common/libecalc/input/mappers/create_references.py
src/ecalc/libraries/libecalc/common/libecalc/input/mappers/facility_input.py
src/ecalc/libraries/libecalc/common/libecalc/input/mappers/fuel_and_emission_mapper.py
src/ecalc/libraries/libecalc/common/libecalc/input/mappers/model.py
src/ecalc/libraries/libecalc/common/libecalc/input/mappers/utils.py
src/ecalc/libraries/libecalc/common/libecalc/input/mappers/variables_mapper/time_series_collection_mapper.py
src/ecalc/libraries/libecalc/common/libecalc/input/yaml/yaml_models/pyyaml_yaml_model.py
src/ecalc/libraries/libecalc/common/libecalc/input/yaml/yaml_models/ruamel_yaml_model.py
src/ecalc/libraries/libecalc/common/libecalc/output/results/dto/dtos.py
src/ecalc/libraries/neqsim/neqsim_ecalc_wrapper/thermo.py

Hopefully make exceptions and tracebacks easier to interpret with explicit context 
Resolves Flake B904, context https://stackoverflow.com/questions/24752395/python-raise-from-usage
Raise exceptions from error in try/except context

refactor: raise exceptions from error

---

.pre-commit-config.yaml
src/ecalc/libraries/libecalc/common/libecalc/common/time_utils.py
src/ecalc/libraries/libecalc/common/libecalc/common/utils/calculate_emission_intensity.py
src/ecalc/libraries/libecalc/common/libecalc/common/utils/rates.py
src/ecalc/libraries/libecalc/common/libecalc/core/consumers/legacy_consumer/consumer_function/direct_expression_consumer_function.py
src/ecalc/libraries/libecalc/common/libecalc/core/models/chart/variable_speed_chart.py
src/ecalc/libraries/libecalc/common/libecalc/core/models/compressor/factory.py
src/ecalc/libraries/libecalc/common/libecalc/core/models/compressor/sampled/compressor_model_sampled.py
src/ecalc/libraries/libecalc/common/libecalc/core/models/compressor/sampled/compressor_model_sampled_1d.py
src/ecalc/libraries/libecalc/common/libecalc/core/models/compressor/sampled/compressor_model_sampled_2d.py
src/ecalc/libraries/libecalc/common/libecalc/core/models/compressor/sampled/compressor_model_sampled_3d.py
src/ecalc/libraries/libecalc/common/libecalc/core/models/compressor/sampled/convex_hull_common.py
src/ecalc/libraries/libecalc/common/libecalc/core/models/compressor/train/single_speed_compressor_train_common_shaft.py
src/ecalc/libraries/libecalc/common/libecalc/dto/models/chart.py
src/ecalc/libraries/libecalc/common/libecalc/dto/models/consumer_system.py
src/ecalc/libraries/libecalc/common/libecalc/dto/models/direct.py
src/ecalc/libraries/libecalc/common/libecalc/dto/models/generator_set.py
src/ecalc/libraries/libecalc/common/libecalc/dto/models/tabulated.py
src/ecalc/libraries/libecalc/common/libecalc/dto/models/turbine.py
src/ecalc/libraries/libecalc/common/libecalc/input/file_io.py
src/ecalc/libraries/libecalc/common/libecalc/input/mappers/model.py
src/ecalc/libraries/libecalc/common/libecalc/input/mappers/utils.py
src/ecalc/libraries/libecalc/common/libecalc/input/mappers/variables_mapper/timeseries_utils.py
src/ecalc/libraries/libecalc/common/libecalc/input/yaml/yaml_models/pyyaml_yaml_model.py
src/ecalc/libraries/libecalc/common/libecalc/input/yaml_entities.py
src/ecalc/libraries/libecalc/common/libecalc/input/yaml_types/components/compressor_system.py
src/ecalc/libraries/libecalc/common/libecalc/input/yaml_types/components/pump_system.py
src/ecalc/libraries/libecalc/common/libecalc/output/results/queries.py
src/ecalc/libraries/libecalc/common/libecalc/output/utils/file_utils.py

Road to strict mode! 740 errors to go, fixed 150 in this PR
Add more typing, try to resolve issues

Refactor: more mypy rules

---

src/ecalc/libraries/libecalc/common/libecalc/input/file_io.py
src/ecalc/libraries/libecalc/common/libecalc/output/flow_diagram/fde_models.py
src/ecalc/libraries/libecalc/common/libecalc/output/utils/file_utils.py
src/ecalc/libraries/neqsim/neqsim_ecalc_wrapper/exceptions.py
src/ecalc/libraries/neqsim/neqsim_ecalc_wrapper/java_service.py

This pull request is needed to increase doc-string coverage
Adds more doc-strings

docs: add docstrings to undocumented functions

---

docs/docs/about/migration_guides/v8-1_to_v8-2.md

Update migration guide with changes for ltp and stp.
https://github.com/equinor/ecalc-engine/issues/4441

docs: update migration guide with ltp- and stp changes

---

docs/docs/changelog/v8-2.md

Update changelog for v.8.2 with changes for ltp- and stp.
https://github.com/equinor/ecalc-engine/issues/4441

docs: update changelog 8.2 with changes for ltp- and stp

---

docs/docs/about/migration_guides/v8-1_to_v8-2.md

Additional information that makes it easier for users to understand underlying changes in eCalc and how/why it affects their models and the results.

docs: how to migrate from 8.1 to 8.2

---

README.md

Dead link in read-me, thanks @ArGr1  for bug-report

_chore: dead link in readme

---

docs/docs/about/migration_guides/v8-1_to_v8-2.md
docs/docs/changelog/v8-2.md

Refine the changelog. we do not want to duplicate info in migration guide and changelog. We need to find a better way to handle changelog. Most likely we want to automatize changelog (which we already do with release-please), but that commit messages should improve in order to be able to use the changelog directly (and possibly filter out irrellevant info)

docs: update changelog for 8.2

---

.github/workflows/release-please.yml

make release please create a PR towards correct branch depending on major, minor (main) or patch (release branch)

ci: create release-please pr against correct branch

---

src/ecalc/libraries/libecalc/common/libecalc/core/consumers/legacy_consumer/consumer_function/utils.py
src/ecalc/libraries/libecalc/common/tests/core/consumers/test_consumer_utils.py

`apply_condition` does not work for multiple streams. If condition(s) are not met, rates for all streams at a time step should be set to 0. This PR fixes that.

fix: make apply_condition work for 2D numpy arrays also

---

poetry.lock
pyproject.toml

up and downgrades that is needed to stay compatible with external dependencies.

chore: update dependencies to be aligned with external requirements

---

.pre-commit-config.yaml
src/ecalc/libraries/libecalc/common/libecalc/common/utils/rates.py
src/ecalc/libraries/libecalc/common/libecalc/core/consumers/legacy_consumer/system/utils.py
src/ecalc/libraries/libecalc/common/libecalc/core/models/compressor/results.py
src/ecalc/libraries/libecalc/common/libecalc/dto/models/compressor/train.py
src/ecalc/libraries/libecalc/common/libecalc/dto/models/turbine.py
src/ecalc/libraries/libecalc/common/libecalc/output/results/dto/dtos.py
src/ecalc/libraries/libecalc/common/tests/core/models/compressor_modelling/test_single_speed_compressor_train_common_shaft.py
src/ecalc/libraries/libecalc/common/tests/core/models/compressor_modelling/test_variable_speed_compressor_train_common_shaft.py
src/ecalc/libraries/libecalc/common/tests/dto/test_composition.py
src/ecalc/libraries/libecalc/common/tests/expression/test_expression_evaluator.py

This pull request is needed because CI fails on main
- Lock version of pydantic used in mypy pre-commit hook
- Update pre-commit hooks
- Resolve new errors in new version of hooks

ci: Lock pydantic version in CI and update hooks

---

src/ecalc/libraries/libecalc/common/libecalc/core/models/compressor/train/utils/enthalpy_calculations.py

This pull request is needed because I could not understand this, so needed to revise the code. Tried to improve the docs slightly
Docs and minor changes

refactor: enthalpy calculations

---

src/ecalc/libraries/libecalc/common/libecalc/core/models/compressor/train/fluid.py
src/ecalc/libraries/libecalc/common/libecalc/core/models/compressor/train/single_speed_compressor_train_common_shaft.py
src/ecalc/libraries/libecalc/common/libecalc/core/models/compressor/train/variable_speed_compressor_train_common_shaft.py

Part 2 of EOS interface
This pull request is needed for simplification
Removes redundant copy statement of FluidStream objects

[Merge Queue]Refactor: remove copy

---

src/ecalc/libraries/libecalc/common/libecalc/common/numbers.py
src/ecalc/libraries/libecalc/common/libecalc/common/utils/rates.py
src/ecalc/libraries/libecalc/common/libecalc/core/consumers/legacy_consumer/result_mapper.py
src/ecalc/libraries/libecalc/common/libecalc/core/models/compressor/train/variable_speed_compressor_train_common_shaft.py
src/ecalc/libraries/libecalc/common/libecalc/core/models/compressor/train/variable_speed_compressor_train_common_shaft_multiple_streams_and_pressures.py
src/ecalc/libraries/libecalc/common/libecalc/expression/expression_evaluator.py
src/ecalc/libraries/libecalc/common/libecalc/input/yaml/yaml_models/pyyaml_yaml_model.py
src/ecalc/libraries/libecalc/common/libecalc/output/flow_diagram/EcalcModelMapper.py
src/ecalc/libraries/libecalc/common/libecalc/output/utils/file_utils.py
src/ecalc/libraries/libecalc/common/tests/input/test_file_io.py

This pull request is needed because to reduce code complexity in ecalc library
- Removes else then if statements with elif
- Remove else then else with single else after elif

[Merge Queue] refactor: reduce branching in if-statements

---

src/ecalc/cli/cli/main.py
src/ecalc/libraries/libecalc/common/libecalc/common/numbers.py
src/ecalc/libraries/libecalc/common/libecalc/common/utils/rates.py
src/ecalc/libraries/libecalc/common/libecalc/core/consumers/legacy_consumer/component.py
src/ecalc/libraries/libecalc/common/libecalc/core/consumers/legacy_consumer/consumer_function/consumer_tabular_energy_function.py
src/ecalc/libraries/libecalc/common/libecalc/core/consumers/legacy_consumer/result_mapper.py
src/ecalc/libraries/libecalc/common/libecalc/core/models/compressor/sampled/compressor_model_sampled_2d.py
src/ecalc/libraries/libecalc/common/libecalc/core/models/compressor/train/base.py
src/ecalc/libraries/libecalc/common/libecalc/core/models/compressor/train/utils/enthalpy_calculations.py
src/ecalc/libraries/libecalc/common/libecalc/core/models/compressor/train/variable_speed_compressor_train_common_shaft.py
src/ecalc/libraries/libecalc/common/libecalc/core/models/compressor/train/variable_speed_compressor_train_common_shaft_multiple_streams_and_pressures.py
src/ecalc/libraries/libecalc/common/libecalc/expression/expression_evaluator.py
src/ecalc/libraries/libecalc/common/libecalc/input/mappers/consumer_function_mapper.py
src/ecalc/libraries/libecalc/common/libecalc/input/yaml/yaml_models/pyyaml_yaml_model.py
src/ecalc/libraries/libecalc/common/libecalc/input/yaml_entities.py
src/ecalc/libraries/libecalc/common/libecalc/output/flow_diagram/EcalcModelMapper.py
src/ecalc/libraries/libecalc/common/libecalc/output/utils/file_utils.py
src/ecalc/libraries/libecalc/common/tests/core/conftest.py
src/ecalc/libraries/libecalc/common/tests/core/models/compressor_modelling/conftest.py
src/ecalc/libraries/libecalc/common/tests/core/models/compressor_modelling/sampled/test_compressor_sampled.py
src/ecalc/libraries/libecalc/common/tests/core/models/test_pump.py
src/ecalc/libraries/libecalc/common/tests/dto/test_categories.py
src/ecalc/libraries/libecalc/common/tests/dto/test_energy_model.py
src/ecalc/libraries/libecalc/common/tests/dto/test_generator_set.py
src/ecalc/libraries/libecalc/common/tests/input/test_file_io.py
src/ecalc/libraries/libecalc/common/tests/integration/test_all_consumer_with_time_slots_models.py

This pull request is needed because blind noqa statements might ignore unexpected errors
Removes noqa where it is not needed

[Merge Queue]Chore: remove unused noqa statements

---

src/ecalc/libraries/libecalc/common/libecalc/core/models/compressor/train/fluid.py
src/ecalc/libraries/neqsim/neqsim_ecalc_wrapper/thermo.py

This pull request is needed to remove NeqSim references from Fluid interface.

refactor: move NeqSimfluid creation into NeqSim wrapper

---

docs/docs/about/modelling/setup/models/compressor_modelling/compressor_charts/index.md

Small error in generic compressor docs - need to add units

docs: fix generic compressor example

---

src/ecalc/libraries/libecalc/common/libecalc/dto/models/compressor/fluid.py

confloat is not a type
Use field with float constraints

chore: fix typing of fluid composition

---

docs/docs/changelog/changelog.md
docs/docs/changelog/v7-0.md
docs/docs/changelog/v7-1.md
docs/docs/changelog/v7-2.md
docs/docs/changelog/v7-3.md
docs/docs/changelog/v7-4.md
docs/docs/changelog/v7-5.md
docs/docs/changelog/v7-6.md
docs/docs/changelog/v8-0.md
docs/docs/changelog/v8-1.md
docs/docs/changelog/v8-2.md
docs/docs/changelog/v8-3.md
docs/docs/changelog/v8-4.md

also had to update layout, description etc,
and also put a placeholder for next version,
assumed to be v8.4

docs: update changelog for v8.3

---

docs/docs/changelog/v8-4.md

Update changelog v8.4: Add requested inlet- and outlet compressor pressures to output.

docs: changelog v8.4 add input compressor pressures to output

---

src/ecalc/libraries/libecalc/common/libecalc/core/graph_result.py
src/ecalc/libraries/libecalc/common/libecalc/dto/models/__init__.py

CompressorSampled does not have a suction pressure and crashed ecalc before this change.

fix: requested pressures not always an attribute

---

docs/docs/about/modelling/workflow/generic_workflow.md

A bug in the mermaid syntax caused the mermaid flowchart not to render.
Also changed from TD to LR, as that seems to cause the separate flowcharts to be abover each other (ironically), making it easier for user to see them, than being next to each other rendering quite small and difficult to read

docs: make mermaid diagram of workflow render correctly

---

src/libecalc/core/graph_result.py

Catch potential problems with new requested pressure feature, and warn user.
Move feature experimental to main method for requested pressures.

chore: move feature experimental to main method for requested pressures

---

src/libecalc/dto/components.py
src/libecalc/input/validation_errors.py

Also fix error message when this fails.

fix: ensure unique names in system v2

---

src/libecalc/dto/components.py
src/libecalc/dto/graph.py

Proper graph implementation, isolate networkx and implementation details.

refactor: use Graph object to build graph

---

src/libecalc/input/yaml_types/components/yaml_installation.py
src/tests/libecalc/input/validation/snapshots/test_validation_json_schemas/test_json_schema_changed/schemas.json

fix: don't require HCEXPORT in editor

---

src/libecalc/core/models/compressor/train/stage.py

ECALC-19
Update error message as requested by users

chore: update zero efficiency error message

---

src/libecalc/input/file_io.py

refactor: add option to skip header validation on resource files

---

docs/docs/changelog/next.md
docs/docs/changelog/v8-4.md
docs/docs/changelog/v8-5.md

docs: update changelog

---

src/libecalc/core/models/compressor/train/simplified_train.py
src/tests/libecalc/core/models/compressor_modelling/test_simplified_compressor_train.py

Patch of https://github.com/equinor/ecalc/pull/263 to v8.5

fix: make iteration loops for simplified train consistent

---

src/libecalc/dto/base.py
src/libecalc/dto/components.py
src/libecalc/presentation/yaml/yaml_types/components/system/yaml_consumer_system.py
src/libecalc/presentation/yaml/yaml_types/components/system/yaml_system_component_conditions.py
src/libecalc/presentation/yaml/yaml_types/components/train/yaml_train.py
src/libecalc/presentation/yaml/yaml_types/components/yaml_base.py
src/libecalc/presentation/yaml/yaml_types/components/yaml_compressor.py
src/libecalc/presentation/yaml/yaml_types/components/yaml_generator_set.py
src/libecalc/presentation/yaml/yaml_types/components/yaml_installation.py
src/libecalc/presentation/yaml/yaml_types/components/yaml_pump.py
src/libecalc/presentation/yaml/yaml_types/yaml_stream.py
src/tests/libecalc/input/validation/snapshots/test_validation_json_schemas/test_json_schema_changed/schemas.json
src/tests/libecalc/input/yaml_types/system/test_system_component_conditions.py

Start of a train v2, yaml and dto
- Add YamlTrain and dto.Train
- Rename Stream to StreamConditions as we have both Stream (from -> to) and StreamConditions (rate, pressure)

feat: train v2 yaml and dto

---

docs/docs/about/references/keywords/REGULARITY.md

This pull request is needed because an error was fixed in REGULARITY.

doc: Keyword REGULARITY has been corrected, an error in example.

---

src/libecalc/common/errors/exceptions.py
src/libecalc/presentation/yaml/mappers/component_mapper.py
src/libecalc/presentation/yaml/mappers/consumer_function_mapper.py
src/libecalc/presentation/yaml/mappers/model.py
src/libecalc/presentation/yaml/mappers/utils.py
src/libecalc/presentation/yaml/yaml_types/components/yaml_compressor.py
src/libecalc/presentation/yaml/yaml_types/components/yaml_pump.py
src/tests/libecalc/input/mappers/test_resolve_fuel.py

Bad error message when reference does not exis
Error message

Ecalc 510 improve error message spelling

---

src/libecalc/dto/result/emission.py
src/libecalc/dto/result/results.py
src/libecalc/infrastructure/file_utils.py
src/libecalc/presentation/simple_result/__init__.py
src/libecalc/presentation/simple_result/simple.py
src/tests/libecalc/presentation/simple_result/test_simple.py

Also reverse the imports/dependency

refactor: move simple result to presentation

---

src/libecalc/presentation/exporter/dto/dtos.py
src/tests/libecalc/output/results/test_dtos.py

Refs: https://equinor-ecalc.atlassian.net/browse/ECALC-64

fix: support mismatching timesteps in ltp delta profile

---

src/libecalc/presentation/simple_result/__init__.py
src/libecalc/presentation/simple_result/simple.py
src/tests/libecalc/presentation/simple_result/test_simple.py

Not used, nor trusted by users.
Refs: https://equinor-ecalc.atlassian.net/browse/ECALC-64

fix: remove interpolation method

---

src/libecalc/presentation/yaml/mappers/variables_mapper/variables_mapper.py
src/libecalc/presentation/yaml/yaml_models/pyyaml_yaml_model.py
src/libecalc/presentation/yaml/yaml_types/time_series/yaml_time_series.py
src/tests/libecalc/input/validation/snapshots/test_validation_json_schemas/test_json_schema_changed/schemas.json

Validate when getting time_series from yaml model.

refactor: use time series collection yaml classes

---

docs/docs/changelog/next.md
docs/docs/changelog/v8-7.md
docs/docs/changelog/v8-8.md

docs: update docs for v8.8 release

---

src/ecalc_neqsim_wrapper/lib/neqsim_version_info.md

Try to stay up to date wrt NeqSim

chore: update neqsim to 2.5.16

---

docs/docs/about/modelling/setup/facility_inputs/pump_modelling/pump_charts.md

This pull request is needed because of unclear definition of Head unit in PUMP_CHART
This pull request change the Head unit to M for the PUMP_CHART

doc: Head unit updated for PUMP_CHART format section

---

src/libecalc/presentation/yaml/yaml_types/components/yaml_base.py
src/libecalc/presentation/yaml/yaml_types/components/yaml_generator_set.py
src/libecalc/presentation/yaml/yaml_types/components/yaml_installation.py
src/libecalc/presentation/yaml/yaml_types/emitters/yaml_venting_emitter.py
src/libecalc/presentation/yaml/yaml_types/fuel_type/yaml_emission.py
src/tests/libecalc/input/validation/snapshots/test_validation_json_schemas/test_json_schema_changed/schemas.json

Adds pattern to json-schema so users get early feedback if name contains invalid characters

fix: add name constraints to yaml classes

---

src/libecalc/common/time_utils.py
src/libecalc/presentation/yaml/mappers/create_references.py
src/tests/ecalc_cli/test_app.py
src/tests/libecalc/dto/utils/test_validators.py

Use EcalcError to make it a handled error.
Refs: https://equinor-ecalc.atlassian.net/browse/ECALC-701

fix: error when creating references

---

src/libecalc/common/utils/rates.py
src/tests/libecalc/common/utils/test_rates.py

Added missing regularity field validator for TimeSeriesRate

---

docs/docs/about/modelling/workflow/generic_workflow.md

This pull request is needed because it makes a more clear explanation about Generic Workflow after Haldis Sylte's review.
This pull request changes at following parts:
1. come corrections in the workflow charts.
2. Explanations at Constant Power Loads of workflow.

doc: updates for Generic Workflow to make a more clear explanation after Haldis Sylte's review.

---

src/ecalc_cli/commands/run.py
src/ecalc_cli/commands/show.py
src/ecalc_neqsim_wrapper/mappings.py
src/libecalc/common/stream_conditions.py
src/libecalc/common/utils/rates.py
src/libecalc/core/consumers/legacy_consumer/component.py
src/libecalc/core/consumers/legacy_consumer/result_mapper.py
src/libecalc/core/consumers/legacy_consumer/system/consumer_function.py
src/libecalc/core/models/chart/variable_speed_chart.py
src/libecalc/core/models/compressor/train/variable_speed_compressor_train_common_shaft_multiple_streams_and_pressures.py
src/libecalc/dto/result/tabular_time_series.py
src/libecalc/presentation/simple_result/simple.py
src/libecalc/presentation/yaml/mappers/variables_mapper/variables_mapper.py
src/tests/ecalc_neqsim_wrapper/conftest.py
src/tests/libecalc/common/test_tabular_time_series.py
src/tests/libecalc/core/models/compressor_modelling/test_simplified_compressor_train.py
src/tests/libecalc/core/models/compressor_modelling/test_variable_speed_compressor_train_common_shaft.py
src/tests/libecalc/core/models/compressor_modelling/test_variable_speed_compressor_train_multiple_streams.py
src/tests/libecalc/core/models/test_energy_function_results.py
src/tests/libecalc/core/result/test_results.py
src/tests/libecalc/dto/test_composition.py
src/tests/libecalc/input/test_parse_input.py
src/tests/libecalc/integration/test_all_consumer_with_time_slots_models.py
src/tests/libecalc/integration/test_consumer_system_v2.py
src/tests/libecalc/output/flow_diagram/test_ecalc_model_mapper.py

Replace with model_dump and model_copy

chore: remove deprecated usage of dict,copy

---

src/libecalc/dto/emission.py
src/libecalc/dto/models/base.py
src/libecalc/dto/models/compressor/base.py
src/libecalc/dto/models/consumer_system.py
src/libecalc/dto/models/direct.py
src/libecalc/dto/models/pump.py
src/libecalc/dto/models/tabulated.py
src/libecalc/dto/result/results.py

validator is deprecated in pydantic v2

chore: use field_validator

---

src/libecalc/presentation/flow_diagram/fde_models.py

Create custom datetime to handle serialization

chore: remove deprecated json_encoders

---

src/tests/ecalc_cli/snapshots/test_app/test_valid/flow-diagram.json

chore: update snapshot for failing test

---

src/libecalc/expression/expression.py

Expression validation does not need to handle list and dict, raising a ValueError passes that on to another validator.

refactor: remove unnecessary collection handling in expression

---

CONTRIBUTING.md
LICENSE
pyproject.toml

chore: switch license to LGPLv3

---

src/libecalc/fixtures/cases/minimal/minimal_yaml.py
src/libecalc/presentation/yaml/mappers/variables_mapper/variables_mapper.py
src/libecalc/presentation/yaml/yaml_models/pyyaml_yaml_model.py
src/libecalc/presentation/yaml/yaml_models/yaml_model.py
src/libecalc/presentation/yaml/yaml_types/components/legacy/energy_usage_model/common.py
src/libecalc/presentation/yaml/yaml_types/components/legacy/energy_usage_model/yaml_energy_usage_model_compressor.py
src/libecalc/presentation/yaml/yaml_types/components/legacy/energy_usage_model/yaml_energy_usage_model_consumer_system.py
src/libecalc/presentation/yaml/yaml_types/components/legacy/energy_usage_model/yaml_energy_usage_model_consumer_system_multiple_streams.py
src/libecalc/presentation/yaml/yaml_types/components/legacy/energy_usage_model/yaml_energy_usage_model_direct.py
src/libecalc/presentation/yaml/yaml_types/components/legacy/energy_usage_model/yaml_energy_usage_model_pump.py
src/libecalc/presentation/yaml/yaml_types/components/legacy/energy_usage_model/yaml_energy_usage_model_tabulated.py
src/libecalc/presentation/yaml/yaml_types/components/system/yaml_consumer_system.py
src/libecalc/presentation/yaml/yaml_types/components/yaml_base.py
src/libecalc/presentation/yaml/yaml_types/components/yaml_expression_type.py
src/libecalc/presentation/yaml/yaml_types/fuel_type/yaml_emission.py
src/libecalc/presentation/yaml/yaml_types/yaml_stream_conditions.py
src/libecalc/presentation/yaml/yaml_validation_context.py
src/tests/libecalc/presentation/yaml/yaml_models/test_pyyaml_yaml_model.py

If a context with expression references are given, the YamlExpressionType will now check that the references in the expression are valid.

feat: validate expression reference tokens

---

src/libecalc/presentation/yaml/yaml_types/models/yaml_compressor_stages.py

fix: add control margin to compressor stage validation

---

poetry.lock

chore: upgrade dependencies

---

src/ecalc_neqsim_wrapper/lib/neqsim_version_info.md

chore: update NeqSim to 2.5.21

---

poetry.lock

Pydantic 2.7 and other dep updates

Update libeCalc deps for 8.13 release

---

src/libecalc/presentation/exporter/configs/configs.py
src/libecalc/presentation/exporter/queries.py
src/libecalc/presentation/yaml/yaml_types/emitters/yaml_venting_emitter.py
src/libecalc/presentation/yaml/yaml_types/yaml_stream_conditions.py
src/tests/libecalc/presentation/yaml/test_venting_emitter.py

* chore: change volume unit venting emitters
ECALC-507

chore: change volume-unit venting emitters (#442)

---

docs/docs/about/references/keywords/CATEGORY.md

Testing automation of tickets
Refs: ECALC-1074

docs: dummy change to docs

---

docs/docs/changelog/v7-2.md

ECALC-1074
Fix typo to test automation

docs: fix typo

---

.github/workflows/create-jira-release.yml
.github/workflows/on-tag-release.yml
scripts/create-jira-release.sh

What a release tag is created we create a release in jira containing all references issues

Automate creation of jira release

---

src/libecalc/application/graph_result.py
src/libecalc/fixtures/cases/venting_emitters/venting_emitter_yaml.py
src/tests/libecalc/output/results/test_ltp.py

* fix: ensure regularity is evaluated for all installations
ECALC-1061
(cherry picked from commit 0e6b2489c97878a848a486faabfa07895d1483ab)

fix: ensure regularity is evaluated for all installations

---

.github/workflows/on-push-main-branch.yml

Using a deployment to be able to move issues when commits are merged to main.

chore: add deploy for jira tracking

---

poetry.lock
pyproject.toml

chore: update typer

---

src/libecalc/core/consumers/legacy_consumer/system/results.py
src/libecalc/expression/expression_evaluator.py

fix: use custom type pydantic class to wrap ndarray and avoid validation problem

---

docs/docs/changelog/v8-15.md

Update changelog for v8.15 to describe fixes for max usage from shore.

docs: update changelog with fixes for max usage from shore

---

.github/workflows/on-manual-create-prerelease.yml

https://equinor-ecalc.atlassian.net/browse/ECALC-1248

chore: add support to manually create prereleases

---

.github/workflows/release-please.yml

chore: make prerelease behave differently

---

.github/workflows/release-please.yml

chore: make prerelease behave differently with vars vars

---

docs/package-lock.json
docs/package.json

chore(docs): update documentation

---

.github/CODEOWNERS

chore: codeowners for changelog

---

src/libecalc/fixtures/cases/all_energy_usage_models/all_models_dto.py
src/libecalc/fixtures/cases/all_energy_usage_models/data/all_energy_usage_models.yaml
src/libecalc/fixtures/cases/venting_emitters/venting_emitter_yaml.py
src/libecalc/presentation/yaml/yaml_types/yaml_stream_conditions.py
src/tests/libecalc/dto/test_categories.py
src/tests/libecalc/output/results/test_ltp.py
src/tests/libecalc/presentation/yaml/test_venting_emitter.py
src/tests/libecalc/presentation/yaml/test_venting_emitter_validation_errors.py

* chore: refine unit format alignment
ECALC-1059

chore: refine unit format alignment (#506)

---

docs/docs/about/migration_guides/v8.15_to_v8.16.md
docs/docs/about/references/keywords/EMISSIONS.md
docs/docs/about/references/keywords/RATE.md
docs/docs/about/references/keywords/UNIT.md
docs/docs/changelog/v8-15.md
docs/docs/changelog/v8-16.md

- Include changelog and migration guide for v8.16. 
- Update docs with new unit format for venting emitters.

docs: update changelog and migration guide

---

docs/docs/about/references/keywords/TURBINE_LOADS.md

docs: change TURBINE_LOAD to TURBINE_LOADS

---

docs/README.md
docs/package-lock.json
docs/package.json

Update search dependency to fix issue with search in docs

fix(docs): issue with anchor links in search

---

src/libecalc/presentation/yaml/yaml_types/models/model_reference_validation.py

Include the turbine name in the error message.
Refs: ECALC-1199

fix: error message for compressor model in turbine

---

src/libecalc/infrastructure/file_io.py

refactor: remove double import

---

docs/docs/changelog/next.md
poetry.lock
pyproject.toml
src/ecalc_cli/main.py
src/libecalc/fixtures/cases/venting_emitters/venting_emitter_yaml.py
src/libecalc/presentation/yaml/model.py
src/libecalc/presentation/yaml/validation_errors.py
src/libecalc/presentation/yaml/yaml_models/pyyaml_yaml_model.py
src/tests/ecalc_cli/test_app.py
src/tests/libecalc/input/mappers/test_model_mapper.py
src/tests/libecalc/input/mappers/variables_mapper/test_timeseries.py
src/tests/libecalc/input/test_validation_errors.py
src/tests/libecalc/presentation/exporter/test_ltp.py
src/tests/libecalc/presentation/yaml/test_venting_emitter_validation_errors.py
src/tests/libecalc/presentation/yaml/yaml_types/models/test_yaml_simplified_compressor_train.py

Use yaml classes for yaml validation.
BREAKING CHANGE: Validation is more strict than before.

feat!: validate yaml model

---

docs/docs/changelog/next.md

Changelog update reflecting fix made in:
https://github.com/equinor/ecalc/pull/589

chore: update changelog with fix in isvalid for compressor stages

---

.gitignore

Some might be working in vscode.
Just add vscode to gitignore under IDE section

chore: add .vscode to gitignore under IDE section

---

src/libecalc/application/energy_calculator.py
src/libecalc/core/consumers/generator_set.py
src/libecalc/core/consumers/legacy_consumer/component.py
src/libecalc/core/models/generator.py
src/tests/libecalc/core/consumers/consumer_function/test_direct_expression_consumer_function.py
src/tests/libecalc/core/consumers/test_genset.py
src/tests/libecalc/core/consumers/test_legacy_consumer.py
src/tests/libecalc/core/models/test_generator_model.py
src/tests/libecalc/integration/test_all_consumer_with_time_slots_models.py

Core should not import other stuff except common.

refactor: avoid using dtos in core

---

poetry.lock
pyproject.toml

Upgrade scipy dependency for Komodo requirement + others
* Only for Python > 3.9

chore: upgrade scipy etc

---

.github/workflows/lib-ci.yml
poetry.lock
pyproject.toml
src/tests/libecalc/presentation/exporter/test_ltp.py

changed resolver for scipy to support latest, and
added support for python 3.12

chore: upgrade deps

---

docs/docs/about/modelling/setup/models/compressor_modelling/compressor_models_types/variable_speed_compressor_train_model.md
docs/docs/about/references/PRESSURE_CONTROL.md

Small fixes to clarify documentation of PRESSURE_CONTROL keyword
ECALC-606

docs: improve documentation around PRESSURE_CONTROL

---

poetry.lock

Ecalc 1626 update dependencies

---

poetry.lock

chore: update deps week 38

---

src/libecalc/presentation/yaml/mappers/create_references.py

This validation is already done per consumer in YamlFuelConsumer and YamlElectricityConsumer

refactor: remove unnecessary validation

---

poetry.lock

chore: update dependencies week 41

---

src/libecalc/fixtures/cases/ltp_export/utilities.py
src/tests/libecalc/presentation/exporter/test_ltp.py
src/tests/libecalc/presentation/yaml/test_venting_emitter.py

Avoid being dependent on order of columns

test: use column id instead of index

---

poetry.lock

chore: upgrade dependencies for week 43

---

src/libecalc/common/errors/exceptions.py
src/libecalc/presentation/yaml/domain/reference_service.py
src/libecalc/presentation/yaml/mappers/component_mapper.py
src/libecalc/presentation/yaml/mappers/consumer_function_mapper.py
src/libecalc/presentation/yaml/mappers/create_references.py
src/libecalc/presentation/yaml/mappers/utils.py
src/libecalc/presentation/yaml/model.py
src/libecalc/presentation/yaml/yaml_entities.py
src/libecalc/presentation/yaml/yaml_types/components/system/yaml_consumer_system.py
src/libecalc/presentation/yaml/yaml_types/components/train/yaml_train.py
src/libecalc/presentation/yaml/yaml_types/components/yaml_compressor.py
src/libecalc/presentation/yaml/yaml_types/components/yaml_pump.py
src/tests/libecalc/input/mappers/test_resolve_fuel.py

- **refactor: reference service interface**

refactor: reference service interface

---

src/libecalc/common/discriminator_fallback.py

- **fix: support python types in DiscriminatorWithFallback**

fix: support python types in DiscriminatorWithFallback

---

src/libecalc/common/utils/rates.py
src/tests/libecalc/common/utils/test_rates.py

Using 'after' when possible makes it easier to only focus on the intention
of the validation. In this case we got problems when validating
data without 'periods'. Validations should always raise ValueError or
AssertionError, in this case it was KeyError.

fix: validate lengths after data validation

---

src/libecalc/application/energy_calculator.py
src/libecalc/common/utils/rates.py

append on timeseries and merge_results is not used.

chore: remove unused code

---

test/README.md

docs: inform how to run tests locally

---

README.md

docs: try to make release-please create pr for 9.1.0

---

docs/package-lock.json
poetry.lock

chore: upgrade dependencies for week 45

---

src/libecalc/core/models/compressor/train/variable_speed_compressor_train_common_shaft.py

1) If the pressure at maximum rate at the maximum speed curve is still too high and the pressure control is DOWNSTREAM_CHOKE, the choke can be used to lower the pressure - so we can still run at maximum rate at the maximum speed curve. We don't need to check for is_valid, as we can choke the pressure down to whatever we want. Also, if the power at that rate is above maximum power, is_valid will be false - and the code will not enter the if-statement as it should.
2) Use calculate_shaft_speed_given_rate_ps_pd instead of evaluate_rate_ps_pd

fix: get max standard rate when compressor train has downstream choke

---

src/libecalc/presentation/yaml/model.py
src/libecalc/presentation/yaml/yaml_models/pyyaml_yaml_model.py

fix: raise error if yaml file is empty or not a valid yaml object

---

docs/config/meta.json
docs/docs/changelog/v9-0.md
docs/docs/changelog/v9-1.md
docs/drafts/next.draft.md

docs: docs were not correctly updated for v9.1 release

---

poetry.lock

chore: upgrade dependencies for week 02. Auto-generated by devCalc

---

.github/workflows/docs-ci.yml
.github/workflows/docs-publish.yml
.github/workflows/examples-ci.yml
.github/workflows/lib-ci.yml
poetry.lock

chore: upgrade dependencies week 2

---

.github/workflows/publish.yml

fix: poetry in pipeline

---

src/libecalc/domain/infrastructure/energy_components/fuel_consumer/fuel_consumer.py
src/libecalc/domain/infrastructure/energy_components/generator_set/generator_set_dto.py
src/libecalc/presentation/yaml/validation_errors.py
tests/libecalc/dto/test_fuel_consumer.py
tests/libecalc/dto/test_generator_set.py

Previous update of ValidationError was not necessary. Handle missing location info in dto (where the error occurs) instead.

chore: revert changes in validation error and update dto exceptions

---

docs/docs/about/migration_guides/v8.20_to_v9.6.md

docs: add missing migration guide change

---

docs/docs/about/migration_guides/v8.20_to_v9.6.md

docs: fix erroneous markdown syntax

---

src/libecalc/domain/infrastructure/energy_components/legacy_consumer/system/consumer_function.py

Convert to np array in pump system
Refs:
https://github.com/equinor/ecalc-internal/discussions/408

fix: issue with list when np array is expected

---

docs/config/meta.json
docs/docs/changelog/v9-10.md
docs/drafts/next.draft.md

release: prepare release of libecalc v9.10.0

---

docs/config/meta.json
docs/docs/changelog/v9-11.md
docs/drafts/next.draft.md

release: prepare release of libecalc v9.11.0

---

src/libecalc/presentation/json_result/result/results.py

Fix problems in api breaking results.

chore: remove intensities from asset dto

---

poetry.lock
pyproject.toml

chore: update rich to v14

---

poetry.lock
src/libecalc/presentation/yaml/yaml_types/components/yaml_asset.py

chore: upgrade dependencies for week 14. Auto-generated by devCalc

---

docs/config/meta.json
docs/docs/changelog/v9-15.md
docs/drafts/next.draft.md

release: prepare release of libecalc v9.15.0

---

src/libecalc/common/errors/exceptions.py
src/libecalc/domain/process/dto/compressor/sampled.py
src/libecalc/domain/process/dto/generator_set.py
src/libecalc/domain/process/dto/tabulated.py
src/libecalc/infrastructure/file_io.py
src/libecalc/presentation/yaml/domain/time_series_resource.py
src/libecalc/presentation/yaml/mappers/facility_input.py
src/libecalc/presentation/yaml/mappers/model.py
src/libecalc/presentation/yaml/mappers/utils.py
src/libecalc/presentation/yaml/model.py
src/libecalc/presentation/yaml/validation_errors.py
tests/libecalc/input/mappers/test_consumer_chart.py
tests/libecalc/presentation/yaml/yaml_types/components/test_fuel_consumer.py

Improve error messages to user.
https://github.com/equinor/ecalc-internal/issues/644

fix: error propegation

---

docs/config/meta.json
docs/docs/changelog/v9-16.md
docs/drafts/next.draft.md

release: prepare release of libecalc v9.16.0

---

docs/package-lock.json
poetry.lock

Fresh PR since the previous one contained unrelated changes!
This also serves as a small poc for this pr: https://github.com/equinor/ecalc-engine/pull/6804 as it was generated from that branch

chore: upgrade dependencies for week 15. Auto-generated by devCalc

---

docs/docs/about/references/POWER_ADJUSTMENT_FACTOR.md

Resolves https://github.com/equinor/ecalc-internal/discussions/721

docs: added explanation about POWER_ADJUSTMENT_FACTOR

---

poetry.lock
pyproject.toml

refs: https://github.com/equinor/ecalc/issues/889

chore: remove click

---

src/libecalc/presentation/yaml/mappers/model.py
src/libecalc/presentation/yaml/mappers/utils.py

https://github.com/equinor/ecalc-internal/issues/755

fix: key error speed

---

poetry.lock

chore: upgrade dependencies for week 21. Auto-generated by devCalc

---

poetry.lock

chore: upgrade dependencies for week 23. Auto-generated by devCalc

---

src/libecalc/domain/process/compressor/core/train/base.py
src/libecalc/domain/process/compressor/core/train/simplified_train.py
tests/libecalc/core/models/compressor_modelling/test_simplified_compressor_train.py
tests/libecalc/core/models/compressor_modelling/test_variable_speed_compressor_train_common_shaft.py
tests/libecalc/core/models/compressor_modelling/test_variable_speed_compressor_train_multiple_streams.py

fix: repair broken get max standard rate code

---

src/libecalc/domain/process/compressor/core/train/base.py

`find_shaft_speed_given_constraints` takes in an upper/lower limit for speed, but does not actually use them.
Potentially leading to errors like this:

fix: actually use the upper and lower bound provided for finding the shaft speed of a compressor train 

---

docs/docs/about/migration_guides/v9.13_to_v10.0.md
docs/docs/about/references/END.md
docs/docs/about/references/START.md

docs: make it clear how start and end works, with good examples

---

poetry.lock

chore: upgrade dependencies for week 35. Auto-generated by devCalc

---

src/ecalc_neqsim_wrapper/lib/neqsim_version_info.md

chore: bump NeqSim version to 3.0.38

---

src/libecalc/presentation/yaml/mappers/model.py

fix: map downstream pressure control from yaml to domain

---

uv.lock

ci: update uv.lock

---

src/libecalc/presentation/yaml/domain/expression_time_series_cable_loss.py
src/libecalc/presentation/yaml/domain/expression_time_series_fluid_density.py
src/libecalc/presentation/yaml/domain/expression_time_series_max_usage_from_shore.py
src/libecalc/presentation/yaml/domain/expression_time_series_power_loss_factor.py
src/libecalc/presentation/yaml/domain/expression_time_series_pressure.py
src/libecalc/presentation/yaml/domain/time_series_expression.py
src/libecalc/presentation/yaml/mappers/component_mapper.py
src/libecalc/presentation/yaml/mappers/consumer_function_mapper.py
tests/conftest.py
tests/libecalc/conftest.py
tests/libecalc/core/conftest.py
tests/libecalc/core/consumers/consumer_function/test_direct_expression_consumer_function.py
tests/libecalc/core/consumers/system/test_consumer_system.py
tests/libecalc/core/models/test_consumer_tabular_energy_function.py
tests/libecalc/domain/infrastructure/energy_components/legacy_consumer/test_tabular_consumer_function.py
tests/libecalc/presentation/yaml/domain/test_time_series_cable_loss.py
tests/libecalc/presentation/yaml/domain/test_time_series_mask.py

chore: remove list of expression from TimeSeriesExpression

---

src/libecalc/domain/infrastructure/energy_components/legacy_consumer/consumer_function/utils.py
src/libecalc/presentation/yaml/domain/time_series_mask.py

fix: ensure that ecalc works with numpy1

---

.github/workflows/on-push-main-branch.yml

ci: fix pipeline

---

docs/config/meta.json
docs/docs/changelog/v11-1.md
docs/drafts/next.draft.md

release: prepare release of libecalc v11.1.0

---

docs/.npmrc
pyproject.toml
requirements.txt
uv.lock

chore: upgrade dependencies for week 41. Auto-generated by devCalc
