equinor/ecalc

- README.md
The readme is copied to PyPI, but the relative image links does not work there.
Changes the image links to be absolute
> chore: change to absolute image links in readme

- .pre-commit-config.yaml
- src/ecalc/libraries/libecalc/common/libecalc/core/models/compressor/train/fluid.py
- src/ecalc/libraries/libecalc/common/tests/core/models/compressor_modelling/test_fluid.py
- src/ecalc/libraries/neqsim/neqsim_ecalc_wrapper/thermo.py
- src/ecalc/libraries/neqsim/tests/integration_tests/test_gerg_fluid.py
- src/ecalc/libraries/neqsim/tests/integration_tests/test_remove_liquid.py
- src/ecalc/libraries/neqsim/tests/unit_tests/test_neqsim_fluid.py
This pull request is needed because the function 'mix_in_fluid' returned both 'NeqSimFluid' and 'Tuple[dict, NeqSimFluid]' leading to a potential bug if you don't know if you get a dict or a NeqSimFluid as output of the function
- Turn on mypy for the neqsimwrapper to avoid future mistakes
- Make consitent casing for units in variable names and functions
- Fix inconsistent return type
> Fix: return of mix in fluid

- .github/workflows/lib-ci.yml
- Dockerfile
- poetry.lock
- pyproject.toml
This pull request is needed because the test suite is slow. Parallelization improves runtime of tests by 2x locally on my machine
- Add xdist as dev-dependency
- Run CI tests with pytest-xdist
> ci: use xdist to parallelize test suite

- src/ecalc/libraries/libecalc/common/libecalc/core/consumers/legacy_consumer/consumer_function/compressor_consumer_function.py
- src/ecalc/libraries/libecalc/common/libecalc/core/consumers/legacy_consumer/consumer_function/consumer_tabular_energy_function.py
- src/ecalc/libraries/libecalc/common/libecalc/core/consumers/legacy_consumer/consumer_function/direct_expression_consumer_function.py
- src/ecalc/libraries/libecalc/common/libecalc/core/consumers/legacy_consumer/consumer_function/pump_consumer_function.py
- src/ecalc/libraries/libecalc/common/libecalc/core/consumers/legacy_consumer/consumer_function/results.py
- src/ecalc/libraries/libecalc/common/libecalc/core/consumers/legacy_consumer/consumer_function/utils.py
- src/ecalc/libraries/libecalc/common/libecalc/core/consumers/legacy_consumer/system/consumer_function.py
- src/ecalc/libraries/libecalc/common/tests/core/consumers/consumer_function/test_consumer_function.py
- src/ecalc/libraries/libecalc/common/tests/core/consumers/system/conftest.py
- src/ecalc/libraries/libecalc/common/tests/core/consumers/system/test_consumer_system.py
- src/ecalc/libraries/libecalc/common/tests/core/consumers/system/test_system_results.py
Today all conditions are applied **after** calculations. Conditions should be applied prior to calculations, so that we don't calculate results we are not interested in - both because those results can be confusing, and to save CPU time.
Tasks:
> Evaluate conditions before calculations

- src/ecalc/libraries/libecalc/common/libecalc/core/models/compressor/train/single_speed_compressor_train_common_shaft.py
The compressor code expects numpy arrays, here a single float was passed.
> fix: cast float to numpy array in function call

- docs/docs/about/references/api/index.md
- docs/make-api-reference.py
The static html files generated by docusaurus can be slightly different in each build, which causes the link to the API reference docs page to sometimes not work.
The link to the API reference page has been changed from a relative link to a full URL which should be more stable
> ci: fix issue with api refernce docs generation

- .github/workflows/on-push-any-branch.yml
- .github/workflows/on-push-main-branch.yml
- .github/workflows/on-push-release-branch.yml
- .github/workflows/release-please.yml
To allow both for easy patching of a release on a separate release branch we need to create a release branch that we can patch and only bump patch versions to when needed.
The patch bump should therefore be reserved for that branch to avoid that a new release on main branch will get a conflicting version. Main will therefore in general only have minor bumps, and a release to release should be a minor bump.
If we want to have a major bump, due to breaking changes or many changes and improvements since a previous major version we should do a manual trigger of release-please with that specified as an argument.
> ci: avoid conflicting releases

- .github/CODEOWNERS
github-actions and a few other meta directories did not get automatic review request due to missing ownership
> ci: set default ownership for source

- .github/workflows/release-please.yml
there are subtle differences in workflows triggered by another gh action and a manually triggered workflow.
fixed to be correct according to documentation.
> ci: fix syntax for gh action workflow

- poetry.lock
- pyproject.toml
- src/ecalc/cli/generate_docs.py
- src/ecalc/cli/typer_cli_stub.py
We use typer-cli to auto-generate the CLI reference for the eCalc CLI. However typer-cli is rarely upgraded and is currently limited to use typer 0.7.0 while typer is at 0.9.0. This restricts us unnecessarily to use the latest typer and is potentially a security concern.
The small portion of the code that we were using in typer-cli have been extracted together with the license details to still be able to use the functionality and avoid the limitation of the typer dependency.
Additionally, this is also a potential problem and limitation in order to have eCalc as a part of Komodo, as it will potentially heavily restrict other packages wrt. Typer version.
> chore: remove limiting dependency typer-cli

- src/ecalc/libraries/libecalc/common/libecalc/core/models/results/compressor.py
- src/ecalc/libraries/libecalc/common/tests/core/models/test_energy_function_results.py
A VariableSpeedCompressorTrainCommonShaftMultipleStreamsAndPressures have some results (or more specifically return of rate input) that are lists within lists. The extend method does not handle these results properly. Currently the extend method will add more lists within a list, but it should extend each of the lists inside a list instead.
> fix: extend lists within lists in compressor train results with multiple streams properly

- src/ecalc/libraries/libecalc/common/libecalc/core/models/compressor/base.py
- src/ecalc/libraries/libecalc/common/libecalc/core/models/compressor/train/base.py
- src/ecalc/libraries/libecalc/common/libecalc/core/models/compressor/train/variable_speed_compressor_train_common_shaft_multiple_streams_and_pressures.py
- src/ecalc/libraries/libecalc/common/tests/core/models/compressor_modelling/test_single_speed_compressor_train_common_shaft.py
- src/ecalc/libraries/libecalc/common/tests/core/models/compressor_modelling/test_variable_speed_compressor_train_common_shaft.py
- src/ecalc/libraries/libecalc/common/tests/core/models/compressor_modelling/test_variable_speed_compressor_train_multiple_streams.py
User experienced extrapolation of results when CONDITION(S) imply that no calculations should be done.
When CONDITION(S) imply that no calculations should be performed for a model, the rate(s) are set to zero for that time step. The time step should still be valid - we do not want extrapolation of results. This means that results for time steps with zero rate(s) should always be considered as valid.
This PR changes the validation of the operational conditions (rate(s), suction/discharge pressures) such that time steps with zero rate(s) are always considered valid, and no failure status will be returned for that time step (even if pressures are zero or negative). Any invalid pressures will still be set to 1, because the may be used in a call to neqsim.
> fix: do not validate operational conditions when rate is zero

- src/ecalc/libraries/libecalc/common/libecalc/core/models/compressor/base.py
- src/ecalc/libraries/libecalc/common/libecalc/core/models/compressor/train/base.py
- src/ecalc/libraries/libecalc/common/libecalc/core/models/compressor/train/variable_speed_compressor_train_common_shaft_multiple_streams_and_pressures.py
- src/ecalc/libraries/libecalc/common/tests/core/models/compressor_modelling/test_single_speed_compressor_train_common_shaft.py
- src/ecalc/libraries/libecalc/common/tests/core/models/compressor_modelling/test_variable_speed_compressor_train_common_shaft.py
- src/ecalc/libraries/libecalc/common/tests/core/models/compressor_modelling/test_variable_speed_compressor_train_multiple_streams.py
If rate is zero, do not perform validation of operational conditions. Disregard any potential invalid rates/pressures to avoid getting into a situation were results are extrapolated when they should not be calculated at all.
> fix: validate operational conditions when rate is zero

- src/ecalc/libraries/libecalc/common/libecalc/expression/expression_evaluator.py
- src/ecalc/libraries/libecalc/common/tests/expression/test_expression_evaluator.py
The expression lexer was missing parsing for scientific notation (e.g. `1.23e-05` or `3.4e7`) for numbers part of an expressions with multiple tokens.
Ex. expression `2 {*} 3.4e-05` would be parsed as tokens `[2, {*}, 3.4, e-05]`, which would give issues as there are no variables named e-05.
> fix: parse scientific notation numbers in expression

- src/ecalc/libraries/libecalc/common/libecalc/output/results/configs/configs.py
All flare variables reported to ltp have installation filter, except for nmvoc. It should be consistent.
> chore: add installation filter to flare nmvoc

- src/ecalc/cli/tests/test_app.py
- src/ecalc/libraries/libecalc/common/libecalc/dto/components.py
- src/ecalc/libraries/libecalc/common/libecalc/examples/simple/model_duplicate_emissions_in_fuel.yaml
- src/ecalc/libraries/libecalc/common/libecalc/examples/simple/model_duplicate_names.yaml
- src/ecalc/libraries/libecalc/common/libecalc/input/mappers/create_references.py
- src/ecalc/libraries/libecalc/common/tests/dto/test_fuel_consumer.py
- Names for `FUEL_TYPE` must be unique across installations in an eCalc model file
- Names for `EMISSIONS` must be unique within one `FUEL_TYPE`
Duplicate names may lead to debug problems e.g. for vector lengths etc. It may also override previous value without the user noticing (e.g. when Ctrl-C Ctrl-V syntax)
https://github.com/equinor/ecalc-engine/issues/3401
> chore: enforce unique fuel type names, and unique emission names within one fuel type

- docs/docs/about/references/keywords/TYPE.md
- docs/docusaurus.config.js
Broken links in docs
Fixes broken links
Throw error on faulty link
> Docs: fix links

- src/ecalc/libraries/libecalc/common/libecalc/core/consumers/legacy_consumer/system/consumer_function.py
- src/ecalc/libraries/libecalc/common/libecalc/core/models/compressor/results.py
- src/ecalc/libraries/libecalc/common/libecalc/core/models/compressor/train/simplified_train.py
- src/ecalc/libraries/libecalc/common/libecalc/core/models/compressor/train/variable_speed_compressor_train_common_shaft.py
- src/ecalc/libraries/libecalc/common/libecalc/core/models/compressor/train/variable_speed_compressor_train_common_shaft_multiple_streams_and_pressures.py
- src/ecalc/libraries/libecalc/common/libecalc/output/flow_diagram/EcalcModelMapper.py
- src/ecalc/libraries/libecalc/common/tests/core/conftest.py
- src/ecalc/libraries/libecalc/common/tests/core/models/compressor_modelling/test_compressor_chart.py
- src/ecalc/libraries/libecalc/common/tests/output/flow_diagram/test_ecalc_model_mapper.py
This pull request is needed because it increases code-readability (Jørgen's highly subjective opinion) but also Ruff PERF401, 25% faster than if for-loop
Replace for-loops with list-comprehension for transforming lists
> [Merge Queue- Start here]refactor: Use a list comprehension to create a transformed list

- src/ecalc/libraries/libecalc/common/libecalc/core/models/compressor/train/fluid.py
- src/ecalc/libraries/libecalc/common/tests/core/models/compressor_modelling/test_fluid.py
Part 1 of creating a strict EOS package interface
Neqsim fluid leaked out into multiple parts of ecalc code, now contained to FluidStream object
Instead of storing the neqsim fluid as a private variable, it is now created when needed
> [Start here]refactor: ensure neqsim fluid is contained to FluidStream object

- src/ecalc/libraries/libecalc/common/libecalc/core/models/compressor/train/fluid.py
- src/ecalc/libraries/neqsim/neqsim_ecalc_wrapper/__init__.py
- src/ecalc/libraries/neqsim/neqsim_ecalc_wrapper/mappings.py
- src/ecalc/libraries/neqsim/neqsim_ecalc_wrapper/thermo.py
- src/ecalc/libraries/neqsim/tests/conftest.py
- src/ecalc/libraries/neqsim/tests/integration_tests/test_remove_liquid.py
Part 3 of NeqSim Interface
When more EOS pacakges are added, the mapping unique to a EoS library should be contained inside that package. eCalc should be agnostic
Need to figure out why all-energy-usage-models change
> [Merge Queue]Refactor: NeqSim mapping

- src/ecalc/libraries/libecalc/common/libecalc/output/utils/file_utils.py
This pull request is needed because no guarantee that the exit() from site module is available at runtime (from Ruf rule PLR1772)
Prefer sys.exit(), as the sys module is guaranteed to exist in all contexts.
> [Merge Queue] Refactor: replace bare exit

- src/ecalc/libraries/libecalc/common/libecalc/input/file_io.py
- src/ecalc/libraries/libecalc/common/tests/input/test_file_io.py
This pull request is needed because of wierd bug reported where thousand spacer was used and the error was not catched until NeqSim threw an NaN error
Removes initial and separator spaces when reading csvs
closes: https://github.com/equinor/ecalc-engine/issues/4661
> fix: parse spaces as thousand separators from excel

- docs/docs/about/references/keywords/ENERGY_USAGE_MODEL.md
- docs/docs/changelog/v8-3.md
Update documentation for `ENERGY_USAGE_MODEL`, and update changelog with breaking change: energy model type is not allowed to change over time within a consumer.
https://github.com/equinor/ecalc-engine/issues/4635
> docs: update docs and changelog for energy models

- docs/docusaurus.config.js
The url to the katex css was not updated with the base url.
> chore(docs): fix equations showing twice

- docs/docs/about/modelling/workflow/generic_workflow.md
Seems that mkdocs doesnt understand some directives in the beginning in the mermaid syntax. Also changed to render them above each other in order to see them better.
> docs: make mermaid workflow diagram render correctly

- src/ecalc/libraries/libecalc/common/libecalc/expression/expression.py
- src/ecalc/libraries/libecalc/common/libecalc/input/yaml_types/components/base.py
- src/ecalc/libraries/libecalc/common/libecalc/input/yaml_types/components/compressor_system.py
- src/ecalc/libraries/libecalc/common/libecalc/input/yaml_types/components/pump_system.py
- src/ecalc/libraries/libecalc/common/tests/input/validation/snapshots/test_validation_json_schemas/test_json_schema_changed/schemas.json
Only str was allowed for expressions in the yaml models for system v2 (yellow mark because of json-schema)
Sets the type of expression to a union of int, float and str
> fix: expression type in system v2

- src/ecalc/libraries/libecalc/common/libecalc/input/validation_errors.py
Difficult to understand what the dto validation is related to when there is no reference to the consumer name.
Improve dto validation error to include consumer/component name.
https://equinor-ecalc.atlassian.net/browse/ECALC-21?atlOrigin=eyJpIjoiNjhhMzljMTg5YTk3NDViODgyZGM2ZWY0ZjM0YjM1ODIiLCJwIjoiaiJ9
> ECALC-21 chore: improve dto validation error message

- src/ecalc/libraries/libecalc/common/libecalc/core/graph_result.py
componentType is set to component level in asset_result_dto (get_asset_result). Should be set to component type.
Update componentType in asset_result_dto.
https://equinor-ecalc.atlassian.net/browse/ECALC-179
> fix: component type set to component level in asset dto

- src/ecalc/libraries/libecalc/common/libecalc/common/utils/rates.py
Use camel_case alias in TimeSeries so the json-serialization will be camelCase.
> fix: rate_type was snake_case in json output

- src/ecalc/libraries/libecalc/common/libecalc/core/models/compressor/train/fluid.py
- src/ecalc/libraries/libecalc/common/libecalc/core/models/compressor/train/variable_speed_compressor_train_common_shaft_multiple_streams_and_pressures.py
- src/ecalc/libraries/libecalc/common/tests/core/models/compressor_modelling/test_variable_speed_compressor_train_multiple_streams.py
This regards VairableSpeedCompressorTrainCommonShaftMultipleStreamsAndPressures only. In situations where there is both an additional ingoing stream and an additional ingoing stream between two compressors, one can end up with a situation where one tries to mix together two streams with zero mass rate (to mix the one stream passing from compressor 1 to compressor 2 and the additional stream entering the compressor train between compressor 1 and compressor 2). This means that if we look at this time step isolated there is an unknown composition to recirculate in the second compressor. This fluid to recirculate should have the same composition as the fluid passing through the second compressor at the previous time step.
- Includes a class attribute keeping track of the composition of the …
> fix: what fluid to recirculate when there is no rate entering a compressor stage in a multiple streams compressor train at a given time step

- src/ecalc/libraries/libecalc/common/libecalc/input/mappers/model.py
Keyword `CURVES` is reserved for _variable_ speed compressors only. _Single_ speed compressors should use the keyword `CURVE`. Due to the obvious similarity it is a risk that the user mixes the two, e.g. using `CURVES` for single speed compressors. When this happens the error message is difficult to understand.
- Improve error message when `CURVES` is used for single speed compressor models
- Improve error message when the keyword CURVE is not found (typo etc.) in general, for single speed compressor models.
https://equinor-ecalc.atlassian.net/browse/ECALC-20?atlOrigin=eyJpIjoiOTBjOWU5M2VjOGQwNDdmOWFkOWIxYjlhM2ExYThmNTQiLCJwIjoiaiJ9
> refactor: improve error message when wrong CURVE-keyword input to single speed compressor

- src/ecalc/libraries/libecalc/common/libecalc/input/yaml_types/yaml_temporal_model.py
- src/ecalc/libraries/libecalc/common/libecalc/input/yaml_types/yaml_variable.py
- src/ecalc/libraries/libecalc/common/tests/input/validation/snapshots/test_validation_json_schemas/test_json_schema_changed/schemas.json
- src/ecalc/libraries/libecalc/common/tests/input/validation/test_validation_json_schemas.py
- src/ecalc/libraries/libecalc/common/tests/input/yaml_types/test_yaml_temporal_model.py
See the commits separately.
1:
[fix: handle dates in yaml correctly](https://github.com/equinor/ecalc/pull/154/commits/ea31a24f31fecd35108c62eeb522904e6c3d31dd)
if we dont explicitly handle dates with our own date type, then
PyYAML will change to datetime.date for what we want to have
datetime.datetime. To make sure that all are converted to
datetime.datetime, we set all dates in yaml as our date type.
> Handle dates corectly in yaml

- src/ecalc/libraries/libecalc/common/libecalc/core/consumers/consumer_system.py
- src/ecalc/libraries/libecalc/common/tests/core/consumers/test_crossover.py
tests: add tests for crossover calculation
Exceeding flow can be handled with crossover in
consumer system. The function that calculated it
was hard to understand and verify. Adding tests shows
that this is not working correctly (commented tests).
Hopefully this makes it easier to understand and to fix the
crossover function to work correctly
> add tests for crossover calculation

- src/ecalc/libraries/libecalc/common/libecalc/core/consumers/consumer_system.py
- src/ecalc/libraries/libecalc/common/tests/core/consumers/test_crossover.py
When we had to reduce several rates to get within capacity we set the remaining crossover to a negative value, which then caused issues as we subtracted the remaining crossover from the next rate.
> fix: issue with crossover rate calculation in system v2

- src/ecalc/libraries/libecalc/common/libecalc/input/file_io.py
- src/ecalc/libraries/libecalc/common/tests/input/test_file_io.py
Add check for missing headers in resource CSV files, and more validation tests .
Missing headers will be named "Unnamed: 1" etc by pandas.
> ECALC-201 - chore: add validation for missing headers in csv resource file

- pyproject.toml
When restructuring libecalc the previous mappings
for which packages was removed for simplicity. We
need to include those in order to make poetry/pip
include the required packages in src/ directory, since it will only include libecalc by default (it will look for src dir and package name). It is nevertheless better to be explicit.
The current functionality is the same way as it worked before it failed.
> fix: make ecalc installable again

- src/libecalc/common/tabular_time_series.py
- src/libecalc/common/utils/rates.py
- src/libecalc/core/result/results.py
- src/tests/libecalc/common/test_tabular_time_series.py
- src/tests/libecalc/common/utils/test_rates.py
Make the merge functionality easier to reuse and extend.
> refactor: merge functionality for results

- src/libecalc/expression/expression_evaluator.py
- src/tests/ecalc_cli/snapshots/test_app/test_json_true/test_v3.json
- src/tests/ecalc_cli/snapshots/test_app/test_json_true_detailed_output/test_full_json_v3.json
- src/tests/libecalc/expression/test_expression.py
Removing conversion of NaN to numeric value (0) in expressions introduces challenges with several existing asset models, especially related to zero-division (rates). This will make many models fail. Hence, the conversion of NaN to numeric (0) is added back. This is a short term solution. On the long term a more robust way of handling NaN should be used.
https://equinor-ecalc.atlassian.net/browse/ECALC-234?atlOrigin=eyJpIjoiMjVkOTgzOTlkNDc3NDVmNDhjMmQ0NmVkZTc1NTU1YjEiLCJwIjoiaiJ9
> chore: revert nan to num in expressions

- docs/docs/about/migration_guides/v7_to_v8.md
- docs/docs/about/migration_guides/v8-1_to_v8-2.md
- docs/docs/about/migration_guides/v8-2_to_v8-3.md
- docs/docs/about/migration_guides/v8-3_to_v8-4.md
- docs/docs/changelog/next.md
- docs/docs/changelog/separator.md
- docs/docs/changelog/v7-0.md
- docs/docs/changelog/v7-1.md
- docs/docs/changelog/v7-2.md
- docs/docs/changelog/v7-3.md
- docs/docs/changelog/v7-4.md
- docs/docs/changelog/v7-5.md
- docs/docs/changelog/v7-6.md
- docs/docs/changelog/v8-0.md
- docs/docs/changelog/v8-1.md
- docs/docs/changelog/v8-2.md
- docs/docs/changelog/v8-3.md
- docs/docs/changelog/v8-4.md
changed structure a bit to make it easier to update changelog and index for upcoming releases.
when entering changelog, one would by default look at the current release (that is out), and next release would be just under. below those, the releases are listed chronologically.
When should we delete old changelogs? We have changelogs back to v7...
Or perhaps a separate section to archive for previous major releases?
> docs: update changelog for upcoming release v8.4

- .github/workflows/release-please.yml
- src/libecalc/version.py
Incorrect version.py file was referred to in
release-please, and hence the version within libecalc was not updated. showing v8.3.0 even though it was v8.4.0.
> chore: version must be updated in version.py

- src/libecalc/core/consumers/consumer_system.py
- src/libecalc/core/ecalc.py
- src/libecalc/dto/components.py
- src/libecalc/dto/core_specs/system/operational_settings.py
- src/libecalc/fixtures/cases/consumer_system_v2/consumer_system_v2_dto.py
- src/libecalc/fixtures/cases/consumer_system_v2/data/consumer_system_v2.yaml
- src/libecalc/input/yaml_types/components/system/yaml_compressor_system.py
- src/libecalc/input/yaml_types/components/system/yaml_pump_system.py
- src/libecalc/input/yaml_types/components/system/yaml_system_component_conditions.py
- src/libecalc/input/yaml_types/components/yaml_base.py
- src/tests/libecalc/input/validation/snapshots/test_validation_json_schemas/test_json_schema_changed/schemas.json
Only allow a single crossover, not change it over time.
Make it more clear that operational settings only contain stream conditions for consumers. Rename coming.
> refactor: move crossover to component_conditions for system v2

- src/libecalc/core/graph_result.py
When multiple streams are used we sum the rates to fit the expected result.
> fix: rate when multiple streams model

- src/libecalc/common/utils/rates.py
Set regularity should not raise error when value is wrong, and I think we need to raise ValueError for pydantic to pick it up correctly, if we wanted to raise an error.
> fix: set_regularity fixture

- src/ecalc_cli/commands/run.py
- src/ecalc_cli/commands/selftest.py
- src/ecalc_cli/commands/show.py
- src/ecalc_cli/io/cache.py
- src/ecalc_cli/io/output.py
- src/ecalc_cli/main.py
- src/libecalc/core/models/compressor/train/stage.py
Added to give a more informative "division by zero" error when polytropic efficiency is 0.
> ECALC-19 - Check for zero efficiency

- src/libecalc/common/feature_flags.py
- src/libecalc/core/graph_result.py
- src/libecalc/dto/result/results.py
Extracting requested inlet- and outlet pressure does not work correctly for compressor systems:
When using `SUCTION_PRESSURES` or `DISCHARGE_PRESSURES` there are one pressure per component in the system. This list of pressures is not captured and the pressures are set to nan, and then nan to num (0).
- Update `get_requested_compressor_pressures` in `graph_result`, to select correct pressures for compressors in system
- Ensure correct operational setting is used for the compressors in the system
https://equinor-ecalc.atlassian.net/browse/ECALC-252?atlOrigin=eyJpIjoiYTJiZGUwNmY5MjlhNGMwMjg5YTc1Y2FiNTY0ZTkxNDQiLCJwIjoiaiJ9
> chore: handle requested pressures for compressor systems

- docs/docs/changelog/next.md
- src/libecalc/fixtures/cases/ltp_export/installation_setup.py
- src/libecalc/output/results/configs/configs.py
- src/tests/libecalc/output/results/test_ltp.py
Calculation of nmvoc-emissions for the `BOILER`- and `HEATER` ltp-categories are wrong. The emission query asks for nox instead of nmvoc.
Update emission query to ask for correct emission type.
https://equinor-ecalc.atlassian.net/browse/ECALC-313?atlOrigin=eyJpIjoiM2EwY2MwYzQ4ZTRiNGY5ZGEzZmMyMTgyNjAwYTJiYWMiLCJwIjoiaiJ9
> fix: wrong data for boilers and heaters in ltp-results

- examples/simple_python_model.ipynb
- src/libecalc/common/utils/rates.py
- src/libecalc/core/consumers/legacy_consumer/consumer_function/direct_expression_consumer_function.py
- src/libecalc/core/graph_result.py
- src/libecalc/dto/components.py
- src/libecalc/dto/models/direct.py
- src/libecalc/dto/types.py
- src/libecalc/fixtures/cases/all_energy_usage_models/all_models_dto.py
- src/libecalc/fixtures/cases/ltp_export/installation_setup.py
- src/libecalc/input/mappers/consumer_function_mapper.py
- src/tests/libecalc/common/utils/test_compute_emission_intensity_yearly.py
- src/tests/libecalc/common/utils/test_rates.py
- src/tests/libecalc/core/consumers/conftest.py
- src/tests/libecalc/core/consumers/consumer_function/test_direct_expression_consumer_function.py
- src/tests/libecalc/core/consumers/test_legacy_consumer.py
- src/tests/libecalc/core/models/test_fuel_model.py
- src/tests/libecalc/input/mappers/test_energy_usage_model.py
- src/tests/libecalc/integration/test_multiple_installations.py
libecalc.common should not import from libecalc.dto
> refactor: move RateType into common module

- src/libecalc/core/models/compressor/train/simplified_train.py
- src/tests/libecalc/core/models/compressor_modelling/test_simplified_compressor_train.py
https://github.com/equinor/ecalc/blob/883b7e6888d5ff4ddca41cbeac0f7c7dd96e60a6/src/libecalc/core/models/compressor/train/simplified_train.py#L481 and https://github.com/equinor/ecalc/blob/883b7e6888d5ff4ddca41cbeac0f7c7dd96e60a6/src/libecalc/core/models/compressor/train/utils/enthalpy_calculations.py#L20 both have the same iterative loop changing z and kappa, but the algorithm for finding the max rate has an extra update in the end (https://github.com/equinor/ecalc/blob/883b7e6888d5ff4ddca41cbeac0f7c7dd96e60a6/src/libecalc/core/models/compressor/train/simplified_train.py#L563). Removing this extra update solves the numerical problems reported in this issue.
ECALC 381
> fix: make iteration loops for simplified train consistent

- src/libecalc/common/utils/rates.py
- src/tests/libecalc/common/utils/test_rates.py
When there is a mismatch between number timesteps and number of time series values, this may be silently ignored. The danger is that a single value or few values are extrapolated, or mapped incorrectly, and therefore getting wrong results.
We should make sure that we always have a 1:1 relationshop between timesteps and values when working with timeseries to make sure that this cannot be a problem.
> chore: make sure no mismatch between timestemps and time series values

- src/libecalc/core/ecalc.py
- src/libecalc/dto/components.py
- src/libecalc/fixtures/cases/consumer_system_v2/consumer_system_v2_dto.py
- src/libecalc/input/yaml_types/components/system/yaml_compressor_system.py
- src/libecalc/input/yaml_types/components/system/yaml_pump_system.py
- src/libecalc/output/flow_diagram/EcalcModelMapper.py
No need to have separate systems for pump and compressor
Creates ConsumerSystem instead of Pump- and CompressorSystem in dto.
> refactor: use common consumer system dto class

- src/libecalc/common/stream_conditions.py
- src/libecalc/core/consumers/base/component.py
- src/libecalc/core/consumers/compressor/component.py
- src/libecalc/core/consumers/consumer_system.py
- src/libecalc/core/consumers/pump/component.py
- src/libecalc/core/models/compressor/base.py
- src/libecalc/core/models/compressor/sampled/compressor_model_sampled.py
- src/libecalc/core/models/compressor/train/base.py
- src/libecalc/core/models/compressor/train/variable_speed_compressor_train_common_shaft_multiple_streams_and_pressures.py
- src/libecalc/core/models/pump/pump.py
- src/libecalc/core/result/results.py
- src/libecalc/dto/components.py
- src/libecalc/dto/core_specs/compressor/operational_settings.py
- src/libecalc/dto/core_specs/pump/operational_settings.py
- src/libecalc/dto/result/results.py
- src/libecalc/fixtures/cases/consumer_system_v2/consumer_system_v2_dto.py
- src/libecalc/presentation/yaml/yaml_types/components/system/yaml_consumer_system.py
- src/libecalc/presentation/yaml/yaml_types/yaml_stream_conditions.py
- src/tests/libecalc/common/test_tabular_time_series.py
- src/tests/libecalc/core/consumers/test_crossover.py
- src/tests/libecalc/input/validation/snapshots/test_validation_json_schemas/test_json_schema_changed/schemas.json
We should use StreamConditions because the Stream is defined as the from, to definition of a stream.
> refactor: rename Stream to StreamConditions

- src/ecalc_cli/io/output.py
- src/libecalc/common/time_utils.py
- src/libecalc/common/utils/rates.py
- src/libecalc/dto/result/tabular_time_series.py
- src/tests/libecalc/common/utils/test_rates.py
Currently, if a reporting frequency other than data defined is chosen, the global time vector is forced to start and end at dates which is part of the requested reporting frequency (e.g. 1st of January for YEARLY). If the start date is in e.g. August 2023, the resampled time series will start 1st of January 2023, and we will start extrapolating the results, before resampling - which is not straightforward. What should be set to nan, what should be set to zero.
This PR adds the start date and the end date from the initial global time vector to the resampled time vector of any frequency. This means that cumulative volumes are kept intact, no volumes are lost. The start and end of the data defined global time vector and the resampled time vector will be the same, but the dates in between …
> Ecalc 125 resampling when first date in resampling frequency is different from first date in global time vector

- src/libecalc/common/priority_optimizer.py
- src/libecalc/core/consumers/consumer_system.py
- src/libecalc/core/ecalc.py
Don't want to deal with priority results outside PriorityOptimizer. 
This only works if we can merge results from core in a generic way. I'm thinking we should introduce ids for all objects to make sure we don't merge objects that should not be merged (i.e. merging on index, but the objects are not the same)
Collect results based on priority used before returning from optimize in PriorityOptimizer
> refactor: collect results in priority optimizer

- src/libecalc/core/models/compressor/results.py
- src/libecalc/core/models/compressor/sampled/compressor_model_sampled.py
- src/tests/libecalc/core/models/test_energy_function_results.py
- src/tests/libecalc/integration/snapshots/test_all_consumer_with_time_slots_models/test_all_consumer_with_time_slots_models_results/all_consumer_with_time_slots_models_v3.json
- src/tests/libecalc/integration/snapshots/test_all_energy_usage_models/test_all_results/all_energy_usage_models_v3.json
- src/tests/libecalc/integration/snapshots/test_consumer_system_v2/test_compressor_system_v2_results/consumer_system_v2-consumer_system_v20/consumer_system_v2.json
Problem when extending time series for compressors across temporal models in `EnergyModelBaseResult.extend()`. This is basically related to how None-values are treated. Two bugs:
- Loss of data: When first temporal model contains `None` and next temporal model contains real values, the merge/extend function evaluates to `None` - ignoring data from second temporal model.
- Mismatch between timesteps and values: When first temporal model contains real values, and next temporal model contains `None`, the merge/extend function evaluates to the values of the first temporal model. The timesteps in the second model are ignored, hence a mismatch between number of timesteps and number of values are introduced for the actual time series.
https://equinor-ecalc.atlassian.net/browse/ECALC-376?atlOrigin …
> fix: wrong handling of values and timesteps in temporal models

- docs/docs/about/migration_guides/v8-6_to_v8-7.md
- docs/docs/about/references/keywords/DIRECT_EMITTERS.md
- docs/docs/about/references/keywords/EMISSION_NAME.md
- docs/docs/about/references/keywords/EMITTER_MODEL.md
- docs/docs/about/references/keywords/VENTING_EMITTERS.md
- docs/docs/changelog/changelog.md
- docs/docs/changelog/v8-7.md
- docs/src/css/custom.css
We have changed from direct to venting emitters, they both have to coexist for a while, since some users are on older versions, and the latest official in Komodo still has direct emitters. It should be quite visible on the page for keyword at which version it was removed, and/or removed, or significantly changed (e.g parameters).
https://equinor-ecalc.atlassian.net/browse/ECALC-525?atlOrigin=eyJpIjoiNWE3ODY5MmJjOWVhNDAxZGJjN2U5MTZlMDJjN2VjZGIiLCJwIjoiaiJ9
> docs: update documentation with info about direct emitters name change

- docs/docs/about/references/keywords/EMITTER_MODEL.md
Previously eCalc has done simplified economical calculations. These have been removed. Some remains are still in the documentation, e.g. a description of emission costs.
Remove costs mentioned in the docs describing the emitter model.
https://equinor-ecalc.atlassian.net/browse/ECALC-515
> docs: remove costs mentioned in docs

- docs/docs/about/modelling/examples/drogon.md
The Drogon example in docs contains some references to fuel price- and tax.
Remove references to fuel price- and tax.
https://equinor-ecalc.atlassian.net/browse/ECALC-546?atlOrigin=eyJpIjoiMWFjMWE4YTUwMTY3NGMxZjhlNmE2ZGNjMjJjMjg1MzgiLCJwIjoiaiJ9
> docs: remove reference to price and tax in drogon example

- src/libecalc/presentation/yaml/yaml_types/emitters/yaml_venting_emitter.py
- src/libecalc/presentation/yaml/yaml_types/yaml_stream_conditions.py
merge issues caused us to continue to use
pydantic v1, while we want to use v2. v2 and
v1 cannot be used at the same time and causes
problems.
> fix: correct fallback to pydantic v1

- src/libecalc/fixtures/cases/ltp_export/loading_storage_ltp_yaml.py
- src/libecalc/presentation/exporter/configs/configs.py
- src/libecalc/presentation/yaml/yaml_types/yaml_stream_conditions.py
- src/tests/libecalc/output/results/test_ltp.py
Currently, `Total Oil Loaded/Stored` is filtered by the category `STORAGE`. There's not always storage related emissions for loaded oil. But all known use cases with storage emissions also have loading emissions, so the category should be changed to `LOADING` to avoid post-processing/workarounds.
https://equinor-ecalc.atlassian.net/browse/ECALC-124?atlOrigin=eyJpIjoiN2IzYzZiNmMxNTczNGUxMjkwOWY2NmU1MTY5ODQ4YTYiLCJwIjoiaiJ9
> chore: change ltp-filter for oil loaded/stored

- docs/docs/about/migration_guides/v8-5_to_v8-6.md
- docs/docs/about/migration_guides/v8-6_to_v8-7.md
Economic details are removed from eCalc v8.5 to v8.6. This is not reflected in the migration guide.
Add migration guide for v8.5 to v8.6.
https://equinor-ecalc.atlassian.net/browse/ECALC-594?atlOrigin=eyJpIjoiMDAwNWFiZWFjMjhiNGQ0NWIwZTY3ODg3NWZjNDIyOWYiLCJwIjoiaiJ9
> docs: update migration guide economics

- docs/docs/about/references/keywords/MAXIMUM_PRESSURE_RATIO_PER_STAGE.md
`MAXIMUM_PRESSURE_RATIO_PER_STAGE` is used in determining the number of compressors/stages in a `SIMPLIFIED_VARIABLE_SPEED_COMPRESSOR_TRAIN` with unknown stages. It is not included with a keyword description in docs.
Include keyword description in docs for `MAXIMUM_PRESSURE_RATIO_PER_STAGE`.
https://equinor-ecalc.atlassian.net/browse/ECALC-575?atlOrigin=eyJpIjoiZjc0MzQzZmE3MTZmNGRiZWFhYWM3NjFhZTEwMTA3Y2MiLCJwIjoiaiJ9
> docs: maximum pressure ratio per stage in docs

- src/libecalc/core/models/compressor/train/simplified_train.py
The option to  define `COMPRESSOR_TRAIN` using `NUMBER_OF_COMPRESSORS` was removed a long time ago. This is not reflected in the docstring for `CompressorTrainSimplified`.
Remove and update docstring.
https://equinor-ecalc.atlassian.net/browse/ECALC-616?atlOrigin=eyJpIjoiZTdmMjc5YTlkY2MxNDY0MTlhNTliODQ5OTI1NDcyOTkiLCJwIjoiaiJ9
> docs: remove docstring for number of compressors

- src/libecalc/common/time_utils.py
- src/libecalc/common/utils/rates.py
- src/tests/libecalc/common/utils/test_rates.py
If a period between two timesteps in the resampled boolean variable corresponds to several periods in the original boolean variable, the resampling method should return False if any of the respecitve periods in the original boolean variable are False. Currently the first boolean value is chosen. This PR aims to fix that.
> fix: resample method for TimeSeriesBoolean

- .github/workflows/lib-ci.yml
- src/libecalc/presentation/yaml/yaml_types/__init__.py
- src/libecalc/presentation/yaml/yaml_types/components/legacy/energy_usage_model/common.py
- src/libecalc/presentation/yaml/yaml_types/components/legacy/energy_usage_model/yaml_energy_usage_model_compressor.py
- src/libecalc/presentation/yaml/yaml_types/components/legacy/energy_usage_model/yaml_energy_usage_model_consumer_system.py
- src/libecalc/presentation/yaml/yaml_types/components/legacy/energy_usage_model/yaml_energy_usage_model_consumer_system_multiple_streams.py
- src/libecalc/presentation/yaml/yaml_types/components/legacy/energy_usage_model/yaml_energy_usage_model_direct.py
- src/libecalc/presentation/yaml/yaml_types/components/legacy/energy_usage_model/yaml_energy_usage_model_pump.py
- src/libecalc/presentation/yaml/yaml_types/components/legacy/energy_usage_model/yaml_energy_usage_model_tabulated.py
- src/tests/libecalc/input/validation/snapshots/test_validation_json_schemas/test_json_schema_changed/schemas.json
Use correct Field (v2) from pydantic. Symptom was that json-schema did not use alias when generating schema.
> chore: remove pydantic.v1 import

- src/libecalc/presentation/yaml/yaml_entities.py
- src/tests/ecalc_cli/test_app.py
- src/tests/libecalc/input/test_file_io.py
Allowing str in resource stream allows for a simpler interface for a resource with a name and read function.
> refactor: allow str in resource stream

- src/libecalc/presentation/yaml/yaml_entities.py
- src/tests/ecalc_cli/test_app.py
- src/tests/libecalc/input/test_file_io.py
This reverts commit fe9f3f2008ee32f2a9614d4c88966e4c5e4831f6.
Overlooked the parameters given to read, i.e. size is passed to read but ignored for str type.
> Revert "refactor: allow str in resource stream (#371)"

- docs/docs/changelog/next.md
- src/libecalc/core/models/compressor/train/single_speed_compressor_train_common_shaft.py
- src/libecalc/core/models/compressor/train/utils/common.py
- src/libecalc/core/models/compressor/train/variable_speed_compressor_train_common_shaft.py
- src/libecalc/core/models/compressor/train/variable_speed_compressor_train_common_shaft_multiple_streams_and_pressures.py
- src/tests/libecalc/core/models/compressor_modelling/test_single_speed_compressor_train_common_shaft.py
- src/tests/libecalc/core/models/compressor_modelling/test_variable_speed_compressor_train_common_shaft.py
Inside get_max_rate for variable speed compressor trains, we find the results for maximum speed and minimum speed for the shaft. If the target discharge pressure is between the discharge pressure at minimum speed and at maximum speed, we iterate on speed between the minimum and maximum speeds until a solution is found giving the correct target discharge pressure. There has been no check that the results and minimum and maximum speeds are actually valid. The result have ended up in situations where the results at minimum speed is invalid, and hence the final result also potentially end up as invalid (when in fact valid solutions exists). Also there has been no check to make sure that the found maximum standard rate requires less power than the maximum power defined for the compressor …
> fix: get_max_rate for single/variable speed compressor trains

- docs/docs/about/references/keywords/RATE.md
- src/libecalc/dto/components.py
- src/libecalc/fixtures/cases/all_energy_usage_models/all_models_dto.py
- src/libecalc/fixtures/cases/venting_emitters/venting_emitter_yaml.py
- src/libecalc/presentation/yaml/mappers/component_mapper.py
- src/libecalc/presentation/yaml/validation_errors.py
- src/libecalc/presentation/yaml/yaml_types/emitters/yaml_venting_emitter.py
- src/libecalc/presentation/yaml/yaml_types/yaml_stream_conditions.py
- src/tests/libecalc/dto/test_categories.py
- src/tests/libecalc/input/validation/snapshots/test_validation_json_schemas/test_json_schema_changed/schemas.json
- src/tests/libecalc/presentation/yaml/test_venting_emitter.py
Difficult for user to understand error message, and where things go wrong, when problems with mandatory keywords in yaml.
https://equinor-ecalc.atlassian.net/browse/ECALC-631?atlOrigin=eyJpIjoiYmM0Y2M5YjFkNGQxNDg5NTg4ZDA5NGFmYTFkZDFjMDQiLCJwIjoiaiJ9
> ECALC-631 chore: improve error messages for mandatory keywords

- src/libecalc/presentation/yaml/mappers/create_references.py
Unclear error message when unknown model type
https://equinor-ecalc.atlassian.net/browse/ECALC-705?atlOrigin=eyJpIjoiNTdjODA1Njg5Yzg3NDM1MzkxZjAxZjcxZTk1OTU4NmUiLCJwIjoiaiJ9
> chore: improve error message when unknown model type

- src/libecalc/application/graph_result.py
- src/libecalc/dto/components.py
- src/libecalc/fixtures/cases/venting_emitters/venting_emitter_yaml.py
- src/libecalc/presentation/yaml/yaml_types/components/yaml_installation.py
- src/tests/libecalc/dto/test_categories.py
- src/tests/libecalc/dto/test_installation.py
- src/tests/libecalc/output/results/test_ltp.py
- src/tests/libecalc/presentation/yaml/test_venting_emitter_validation_errors.py
eCalc will fail if one of the keywords `GENERATORSETS` or `FUELCONSUMERS` is missing. Hence, it is not possible to have a model with only `VENTING_EMITTERS`.
Modify graph_result to accept a model with `VENTING_EMITTERS` only. 
https://equinor-ecalc.atlassian.net/browse/ECALC-772?atlOrigin=eyJpIjoiNjkyMjQ1YmZmMjI4NDAyZjhjMGRlZjc2YmJlY2NlMTAiLCJwIjoiaiJ9
> chore: allow venting emitters without fuelconsumers

- src/libecalc/presentation/yaml/yaml_types/components/yaml_installation.py
- src/tests/libecalc/input/mappers/variables_mapper/test_variables_mapper.py
Improves error messages for hcexport and regularity
> fix: use yaml expression type for installation

- src/libecalc/common/errors/exceptions.py
- src/libecalc/common/time_utils.py
- src/libecalc/presentation/yaml/yaml_models/pyyaml_yaml_model.py
- src/libecalc/presentation/yaml/yaml_types/yaml_temporal_model.py
Validation where a temporal model had invalid dates failed because of error raised that is not ValueError.
Refs: ECALC-763
> fix: issue with invalid dates in temporal model

- docs/docs/about/references/keywords/CONTROL_MARGIN.md
- src/libecalc/core/models/chart/base.py
- src/libecalc/core/models/compressor/train/chart/single_speed_compressor_chart.py
- src/libecalc/core/models/compressor/train/chart/variable_speed_compressor_chart.py
- src/libecalc/core/models/compressor/utils.py
- src/libecalc/presentation/yaml/mappers/model.py
- src/tests/libecalc/core/models/compressor_modelling/test_compressor_chart.py
It has been possible to define a CONTROL_MARGIN on single speed compressor trains, but it has not had any effect. It has always been defaulted to zero.
This PR adds the CONTROL_MARGIN functionality also to single speed compressor charts.
Refs ECALC-947
> feat: add control margin to single speed compressor charts

- docs/docs/about/migration_guides/v8-3_to_v8-4.md
- docs/docs/changelog/v8-4.md
The changelog was missing info on a change that now requires CSV resource files to include headings.
ECALC-931
> docs: update changelog and migration guide for v8.4

- docs/docs/changelog/v8-11.md
- src/libecalc/fixtures/cases/ltp_export/installation_setup.py
- src/libecalc/fixtures/cases/ltp_export/utilities.py
- src/tests/libecalc/output/results/test_ltp.py
ECALC-881
There is no test to verify that total power at installation level is the sum of electrical- and mechanical power. The changelog is also lacking info about breaking changes.
https://equinor-ecalc.atlassian.net/browse/ECALC-881
> test: add test for total power

- src/libecalc/fixtures/cases/venting_emitters/venting_emitter_yaml.py
- src/libecalc/presentation/exporter/configs/configs.py
- src/libecalc/presentation/exporter/queries.py
- src/tests/libecalc/output/results/test_ltp.py
- src/tests/libecalc/presentation/yaml/test_venting_emitter.py
- src/tests/libecalc/presentation/yaml/test_venting_emitter_validation_errors.py
Oil volume query is mistakenly removed in previous PR #424.
> fix: add volume query for venting emitters oil type

- src/libecalc/presentation/exporter/configs/configs.py
- src/libecalc/presentation/exporter/queries.py
- src/libecalc/presentation/yaml/yaml_types/emitters/yaml_venting_emitter.py
- src/libecalc/presentation/yaml/yaml_types/yaml_stream_conditions.py
- src/tests/libecalc/presentation/yaml/test_venting_emitter.py
ECALC-507
Unit for oil rates/volumes in venting emitters of type OIL_VOLUME should be `Sm3` and not `t`.
https://equinor-ecalc.atlassian.net/browse/ECALC-507?focusedCommentId=11764&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-11764
> chore: change volume-unit venting emitters

- docs/docs/about/migration_guides/v8.12_to_v8.13.md
- docs/docs/about/migration_guides/v8.13_to_v8.14.md
- docs/docs/about/references/keywords/CABLE_LOSS.md
- docs/docs/about/references/keywords/EMISSIONS.md
- docs/docs/about/references/keywords/GENERATORSETS.md
- docs/docs/about/references/keywords/MAX_USAGE_FROM_SHORE.md
- docs/docs/about/references/keywords/TYPE.md
- docs/docs/about/references/keywords/VENTING_EMITTERS.md
- docs/docs/about/references/keywords/VOLUME.md
- docs/docs/changelog/v8-12.md
- docs/docs/changelog/v8-13.md
- docs/docs/changelog/v8-14.md
- docs/docs/changelog/v8-15.md
Documentation, changelog and migration guide does not reflect all recent updates. E.g. for venting emitters and power from shore columns.
https://equinor-ecalc.atlassian.net/browse/ECALC-1018?atlOrigin=eyJpIjoiMjQ4N2U4OTkzZGE4NGJjZWIwMTA0OWNmZDNmOWNiYjgiLCJwIjoiaiJ9
> docs: update docs, changelog and migration guide

- docs/docs/about/references/keywords/MAXIMUM_POWER.md
This pull request is needed because a new keyword MAXIMUM_POWER was added in eCalc YAML keywords.
> Docs: added keyword MAXIMUM_POWER in eCalc YAML keyword list.

- src/libecalc/presentation/exporter/queries.py
- src/libecalc/presentation/yaml/yaml_types/emitters/yaml_venting_emitter.py
- src/tests/libecalc/presentation/yaml/test_venting_emitter.py
ECALC-1060
The results are identical when input is `STREAM_DAY` and `CALENDAR_DAY`, for volume calculations of venting emitters of type `OIL_VOLUME`.
https://equinor-ecalc.atlassian.net/browse/ECALC-1060?atlOrigin=eyJpIjoiYjIwMDA0ZDRhMjk1NGI2ZWE5MWM2MmQ5ZDRhZDg1MDgiLCJwIjoiaiJ9
> fix: honor rate type for oil type venting emitter

- src/libecalc/application/graph_result.py
- src/tests/libecalc/output/results/test_ltp.py
ECALC-1061
Error when venting emitters are defined alone, without a generator set - for a given installation. The reason is that the installation results are empty, and the installation regularity cannot be found for the particular venting emitters.
More robust reading of regularity for venting emitters, independent of installation results: Reading from the asset object directly.
https://equinor-ecalc.atlassian.net/browse/ECALC-1061?atlOrigin=eyJpIjoiNWUwMDMwMjkxMzc2NGEyMmJmMGY5ZTg3NTBlOThkZDQiLCJwIjoiaiJ9
> fix: error when only venting emitters are specified for an installation

- .github/pull_request_template.md
We tend to forget common chores such as updating changelong and migration guide, making it difficult for release manager or person assigned to "post release" check what is needed to be updated, both context switching wise and annoying.
PR template
ECALC-1130
> chore: Make sure we remember chores for changes

- src/libecalc/application/graph_result.py
- src/libecalc/fixtures/cases/venting_emitters/venting_emitter_yaml.py
- src/tests/libecalc/output/results/test_ltp.py
ECALC-1061
Installation results is empty if only venting emitters are specified for one installation. A check was done testing if installation result was empty, then regularity was evaluated for all installations. However, this check is not sufficient, as there can be several installations. One may have only venting emitters, while another can have genset and fuel consumers.
Change test: Check if length of installation_results is less than number of installations.
https://equinor-ecalc.atlassian.net/browse/ECALC-1061?atlOrigin=eyJpIjoiMDMwOGIwNzdkZmRiNGJhZDk5ZDBkMmM2YjVhY2Q2NjIiLCJwIjoiaiJ9
> fix: ensure regularity is evaluated for all installations when only venting emitters

- docs/docs/about/references/keywords/EMISSIONS.md
- docs/docs/changelog/v8-15.md
- src/libecalc/presentation/yaml/yaml_types/emitters/yaml_venting_emitter.py
- src/tests/libecalc/integration/snapshots/test_all_energy_usage_models/test_all_results/all_energy_usage_models_v3.json
- src/tests/libecalc/presentation/yaml/test_venting_emitter.py
ECALC-1148
Emission name, e.g. nmVOC and nmvoc, should be case insensitive for venting emitters to avoid splitting/interpreting the same emission type as different types.
Convert input emission names to lower case, for venting emitters.
https://equinor-ecalc.atlassian.net/browse/ECALC-1148?atlOrigin=eyJpIjoiY2YyMmY5N2ExMjk4NDVhY2E4Y2E3ZDZkMTM2Y2YwNDgiLCJwIjoiaiJ9
> chore: make venting emitters emission names case insensitive

- src/libecalc/presentation/yaml/yaml_types/emitters/yaml_venting_emitter.py
- src/tests/libecalc/integration/snapshots/test_all_energy_usage_models/test_all_results/all_energy_usage_models_v3.json
- src/tests/libecalc/presentation/yaml/test_venting_emitter.py
Make venting emitter emission names case insensitive, to avoid problem with splitting into two due to case differences.
> fix: make venting emitters emission names case insensitive 

- .github/workflows/lib-ci.yml
- poetry.lock
- pyproject.toml
fixes #480 
Refs: ECALC-1139
We need to support both Pandas 1.x and 2.0 for Python 3.8, and Pandas 2.x for Python 3.9 and later
Add support for Pandas 1 and 2, and make sure that it works for Python 3.8 and Python 3.9
> chore: add support for pandas v2

- src/libecalc/core/consumers/legacy_consumer/system/results.py
- src/libecalc/expression/expression_evaluator.py
ECALC-965
fixes #482 
When users are using eCalc directly on CLI, they will be met with a few warnings that will most likely be difficult for them to understand, so we should either handle them or silence them. 
The problem is caused by sending numpy.ndarrays directly into pydantic, giving validation problems. Avoiding the problem using custom type PydanticNDArray to wrap numpy.ndarray, and use that type instead of numpy.ndarray directly.
A more long term solution is to return List and Float from core.
https://equinor-ecalc.atlassian.net/browse/ECALC-965?atlOrigin=eyJpIjoiNjUxNmVlMmY4ZWEyNGU5YzhmN2RhM2MyZTY0NGE2OWYiLCJwIjoiaiJ9
> fix: use custom type pydantic class to wrap ndarray and avoid validation problem

- .github/workflows/lib-ci.yml
- poetry.lock
- pyproject.toml
- src/libecalc/dto/components.py
- src/libecalc/expression/expression_evaluator.py
- src/libecalc/fixtures/cases/ltp_export/loading_storage_ltp_yaml.py
- src/libecalc/fixtures/cases/venting_emitters/venting_emitter_yaml.py
Refs: ECALC-994
fixes #486 
We need to support both python 3.8 and 3.11  explicitly. Also verify that we support 3.9 and 3.10. Some dependencies requires different dependency resolution based on python version.
Updates dependency resolutions and packages for all packages needed. Added matrix strategy test to verify this in pipeline. 
ECALC-994
> chore: make sure we support python 3.8 and 3.11

- src/libecalc/presentation/exporter/configs/configs.py
- src/libecalc/presentation/exporter/queries.py
- src/tests/libecalc/output/results/test_ltp.py
ECALC-1190
The unit for `Max Usage from Shore` column in LTP-report is GWh, but should be MW.
Change unit from GWh to MW. In query: remove option for input-unit, it should always be MW.
https://equinor-ecalc.atlassian.net/browse/ECALC-1190?atlOrigin=eyJpIjoiZTc1OTcxYThmMmJhNDU3NThkMDlmOGVkOTMxMmNhZTgiLCJwIjoiaiJ9
> fix: wrong unit max power from shore

- docs/docs/changelog/v8-15.md
- src/libecalc/presentation/yaml/yaml_models/pyyaml_yaml_model.py
- src/tests/libecalc/input/test_file_io.py
ECALC-650
If there are duplicate keys defined in the yaml file (for example several VARIABLES with the same name), the last one will be kept and no error given. 
This PR detects duplicate keys and raises and error pointing to where in the yaml file the problem occurs.
> fix: detect duplicate keys in yaml file and raise error

- .github/workflows/lib-ci.yml
- poetry.lock
- pyproject.toml
- src/libecalc/dto/components.py
- src/libecalc/expression/expression_evaluator.py
- src/libecalc/fixtures/cases/ltp_export/loading_storage_ltp_yaml.py
- src/libecalc/fixtures/cases/venting_emitters/venting_emitter_yaml.py
eCalc 8.15.x is in Komodo, and Komodo will have a release next week, that will last until over summer. We should therefore add our dependency changes to that version, and also following (critical) bug fixes.
Just takes dep updates from main to the 8.15 release branch, and reran poetry lock to update lock file correctly.
ECALC-994
> Ecalc 994 patch 8 15 release branch

- src/libecalc/presentation/yaml/yaml_types/components/yaml_generator_set.py
ECALC-1267
Error occurs when creating error message related to wrong category for power from shore columns/variables (`CABLE_LOSS` and `MAX_USAGE_FROM_SHORE` only valid for category `POWER_FROM_SHORE`)
Use model_fields to obtain titles/names in error message.
https://equinor-ecalc.atlassian.net/browse/ECALC-1267?atlOrigin=eyJpIjoiZWMzNDlhNTI5NmM0NDkwMTgwNTljZTM1ZmQ3NWNkM2QiLCJwIjoiaiJ9
> fix: error message for new pfs columns

- src/libecalc/dto/components.py
- src/libecalc/presentation/yaml/mappers/component_mapper.py
- src/libecalc/presentation/yaml/yaml_types/components/yaml_generator_set.py
- src/tests/libecalc/dto/test_generator_set.py
Validation in CLI does not check if generator set is correct category (POWER-FROM-SHORE) when using CABLE_LOSS and MAX_USAGE_FROM_SHORE, just silently ignore if wrong category.
Update validation for power from shore in CLI.
> chore: align cli validation for power from shore

- src/libecalc/fixtures/cases/all_energy_usage_models/all_models_dto.py
- src/libecalc/fixtures/cases/all_energy_usage_models/data/all_energy_usage_models.yaml
- src/libecalc/fixtures/cases/venting_emitters/venting_emitter_yaml.py
- src/libecalc/presentation/yaml/yaml_types/yaml_stream_conditions.py
- src/tests/libecalc/dto/test_categories.py
- src/tests/libecalc/output/results/test_ltp.py
- src/tests/libecalc/presentation/yaml/test_venting_emitter.py
- src/tests/libecalc/presentation/yaml/test_venting_emitter_validation_errors.py
ECALC-1059
Simplify unit definitions in yaml. It is basically a part of the BREAKING CHANGES belonging to the #495.
Write `SM3_PER_DAY` instead of `STANDARD_CUBIC_METERS_PER_DAY`. Write `KG_PER_DAY` instead of `KILO_PER_DAY`.
https://equinor-ecalc.atlassian.net/browse/ECALC-1059?atlOrigin=eyJpIjoiMzA1NzA0MTdiM2NhNDE0YmFiYTBlZmY3N2E1MzMyNjkiLCJwIjoiaiJ9
> chore: refine unit format alignment

- src/libecalc/presentation/yaml/file_context.py
- src/libecalc/presentation/yaml/validation_errors.py
- src/libecalc/presentation/yaml/yaml_models/exceptions.py
- src/libecalc/presentation/yaml/yaml_models/pyyaml_yaml_model.py
- src/libecalc/presentation/yaml/yaml_models/ruamel_yaml_model.py
- src/tests/ecalc_cli/test_app.py
- src/tests/libecalc/input/test_file_io.py
- src/tests/libecalc/presentation/yaml/yaml_models/test_pyyaml_yaml_model.py
- src/tests/libecalc/presentation/yaml/yaml_models/test_yaml_model_errors.py
YamlError gives additional info about the error in yaml, in addition to ensuring a consistent interface across different yaml readers.
> fix: implement YamlModel specific errors

- src/libecalc/presentation/yaml/validation_errors.py
- src/tests/libecalc/input/mappers/variables_mapper/test_timeseries.py
ECALC-647
Difficult to understand error messages related to invalid characters in VARIABLES names, no information about where the issue is in the eCalc model.
Included validation errors of type `string_pattern_mismatch` into CUSTOM_MESSAGES, to ensure better and customized feedback to user for these kind of errors.
https://equinor-ecalc.atlassian.net/browse/ECALC-647?atlOrigin=eyJpIjoiZmY2NzNlNWE2NTdjNGE5MjhmOTEzYWZlNzQ2Yjg4MzEiLCJwIjoiaiJ9
> chore: improve error messages for invalid characters in variables names

- docs/docs/about/references/keywords/EMISSIONS.md
- docs/docs/about/references/keywords/VENTING_EMITTERS.md
- docs/docs/about/references/keywords/VOLUME.md
ECALC-1334
All units for venting emitters have been changed to align with yaml input. This should be reflected in all parts of docs. Some examples still have old units.
Update docs to have correct units for venting emitters.
https://equinor-ecalc.atlassian.net/browse/ECALC-1334?atlOrigin=eyJpIjoiZmZmNGJhNmFhYzJmNGMzZWEzY2VlMTdmMDZiZmJkZDIiLCJwIjoiaiJ9
> docs: wrong units venting emitters docs

- src/libecalc/domain/tabular/tabular.py
- src/libecalc/presentation/exporter/dto/dtos.py
- src/libecalc/presentation/exporter/formatters/formatter.py
- src/tests/libecalc/presentation/exporter/formatters/test_csv_formatter.py
Create reusable protocols for data that is table-like.
HasColumn requires get_title instead of specific attributes, i.e. the title of a column is decided by the column instead of the formatter in this case.
> refactor: reusable protocols for tabular data

- src/libecalc/presentation/json_result/mapper.py
Instead of relying on pydantic conversion or str behavior of enum we pass the string value directly.
> fix: pass enum value to literal string type

- src/libecalc/dto/components.py
- src/libecalc/presentation/yaml/ltp_validation.py
- src/libecalc/presentation/yaml/yaml_types/components/yaml_generator_set.py
- src/tests/libecalc/dto/test_generator_set.py
ECALC-1342
Error message if illegal category is used for extra power from shore columns (`CABLE_LOSS` and `MAX_USAGE_FROM_SHORE`) is the same, even if only one of them is used in the model. Can be confusing for user.
https://equinor-ecalc.atlassian.net/browse/ECALC-1342?atlOrigin=eyJpIjoiMzljZmE4MjlkZWZjNGFmM2EwYmIxNDU4ZGQyNTdkOWUiLCJwIjoiaiJ9
> chore: improve error message for extra pfs columns

- src/libecalc/presentation/yaml/energy_model_validation.py
- src/libecalc/presentation/yaml/mappers/create_references.py
- src/libecalc/presentation/yaml/yaml_types/components/legacy/yaml_electricity_consumer.py
- src/libecalc/presentation/yaml/yaml_types/components/legacy/yaml_fuel_consumer.py
- src/tests/ecalc_cli/test_app.py
ECALC-1026
It should not be allowed to switch types of energy_usage_models when using temporal models. We already have validation for this in the dto objects, and similar should be done in the yaml validation 
https://equinor-ecalc.atlassian.net/browse/ECALC-1026?atlOrigin=eyJpIjoiZTczNDgyYjNmYWY5NGM4Y2FiZmQxODMwY2Q2NGFlMzQiLCJwIjoiaiJ9
> chore: do not allow multiple energy model types

- src/libecalc/common/time_utils.py
- src/libecalc/presentation/json_result/mapper.py
- src/tests/libecalc/common/test_time_utils.py
- src/tests/libecalc/dto/results/model/test_requested_pressures_compressors.py
ECALC-1230
eCalc fails when extracting requested pressures from compressor system, if the date for the temporal model is not included in the timesteps for the input data.
Update method for extracting requested pressures.
https://equinor-ecalc.atlassian.net/browse/ECALC-1230?atlOrigin=eyJpIjoiNTFiNjQ5ZTI2N2ZiNDY5YmJjZGZiM2M3YjM0OGM3YzYiLCJwIjoiaiJ9
> fix: read requested pressures in compressor system

- src/libecalc/common/time_utils.py
Typo in docstring for get_timesteps method. One word.
> fix: typo get timesteps docstring

- src/libecalc/dto/models/chart.py
BREAKING CHANGE: 0 efficiency is not allowed in input charts.
ECALC-977
Errors with 0 efficiency in input chart is catched late, and the error message does not point to the actual input file with the problem.
Do not allow 0 efficiency in input file. It will give feedback much earlier, and points to the relevant file.
https://equinor-ecalc.atlassian.net/browse/ECALC-977?atlOrigin=eyJpIjoiZDljMWJlYTczYzhjNGMwMTliM2FjNjU2YzVlNzJlNTAiLCJwIjoiaiJ9
> chore!: do not allow 0 efficiency in input chart

- src/libecalc/presentation/yaml/mappers/model.py
- src/libecalc/presentation/yaml/yaml_types/models/yaml_compressor_trains.py
- src/tests/libecalc/presentation/yaml/yaml_types/models/test_yaml_simplified_compressor_train.py
BREAKING CHANGE: `CONTROL_MARGIN` not allowed for `SIMPLIFIED_VARIABLE_SPEED_COMPRESSOR_TRAIN`
ECALC-1483
Adding a `CONTROL_MARGIN` to `SIMPLIFIED_VARIABLE_SPEED_COMPRESSOR_TRAIN` has no effect. eCalc ignores it, but user is not notified. 
New behavior: eCalc will fail if `CONTROL_MARGIN` is specified (only pydantic yaml-validation for web, not cli)
https://equinor-ecalc.atlassian.net/browse/ECALC-1483?atlOrigin=eyJpIjoiN2M0OWMzMTFiN2FlNDFkMDg1MmViNTdiODM2NTdjMDYiLCJwIjoiaiJ9
> chore!: do not allow control margin for simplified variable speed train

- src/libecalc/presentation/yaml/mappers/model.py
- src/libecalc/presentation/yaml/yaml_types/models/yaml_compressor_stages.py
- src/libecalc/presentation/yaml/yaml_types/models/yaml_compressor_trains.py
- src/tests/libecalc/presentation/yaml/yaml_types/models/test_yaml_simplified_compressor_train.py
BREAKING CHANGE: `PRESSURE_DROP_AHEAD_OF_STAGE` not allowed for `SIMPLIFIED_VARIABLE_SPEED_COMPRESSOR_TRAIN`
ECALC-1512
Defining `PRESSURE_DROP_AHEAD_OF_STAGE` for a `SIMPLIFIED_VARIABLE_SPEED_COMPRESSOR_TRAIN` does not have any effect. eCalc allows it to be specified in the yaml, but silently ignores it.
https://equinor-ecalc.atlassian.net/browse/ECALC-1512?atlOrigin=eyJpIjoiMTEzOGZkMjdmMzM2NDgzMWFjMGJjZjA5NGUxZDU2ZjciLCJwIjoiaiJ9
> chore!: do not allow pressure drop ahead of stage for simplified trains

- docs/docs/changelog/v8-16.md
- docs/docs/changelog/v8-17.md
- docs/docs/changelog/v8-18.md
- docs/docs/changelog/v8-19.md
- docs/docs/changelog/v8-20.md
- docs/docs/changelog/v8-21.md
ECALC-1565
We dont have individual changelogs for libeCalc since 8.16. Add changelog to 8.17 to 8.21.
Create individual changelogs fro 8.17 to 8.21.
https://equinor-ecalc.atlassian.net/browse/ECALC-1565?atlOrigin=eyJpIjoiZjBmZDhhMWMyMzJhNGJlYmE5ZTBkYmQyNWQ4NzNmMjkiLCJwIjoiaiJ9
> docs: update changelogs

- docs/docs/about/migration_guides/v8-1_to_v8-2.md
- docs/docs/about/migration_guides/v8-2_to_v8-3.md
- docs/docs/about/migration_guides/v8-3_to_v8-4.md
- docs/docs/about/migration_guides/v8-5_to_v8-6.md
- docs/docs/about/migration_guides/v8-6_to_v8-7.md
- docs/docs/about/migration_guides/v8.12_to_v8.13.md
- docs/docs/about/migration_guides/v8.13_to_v8.14.md
- docs/docs/about/migration_guides/v8.15_to_v8.16.md
- docs/docs/about/migration_guides/v8.7_to_v8.8.md
- docs/docs/about/migration_guides/v8_to_v81.md
ECALC-1246
Have the most important (i.e. last updated) info at the top, and align with changelog.
Swap order of migration guide versions.
https://equinor-ecalc.atlassian.net/browse/ECALC-1246?atlOrigin=eyJpIjoiYmY1MWU2MWQ2MmU2NDUzYzlhYTk4ZTZlZDFhZDFjY2MiLCJwIjoiaiJ9
> docs: swap order of migration guides

- src/libecalc/presentation/yaml/yaml_models/ruamel_yaml_model.py
Implement get_validator which raises NotImplementedError to avoid RuamelYamlModel becoming abstract.
> fix: avoid RuamelYamlModel becoming an abstract class

- docs/docs/about/modelling/setup/models/compressor_modelling/compressor_models_types/simplified_variable_speed_compressor_train_model.md
Ref. ECALC-1331 issue about missing required units in example _"A compressor train where the number of stages are unknown"_in section _"Simplified variable speed compressor train"_.
- Added some newlines some places to adhere to general doc styling. 
- Added POLYTROPIC_EFFICIENCY and UNITS, same as as found in the GENERIC_FROM_INPUT example in the compressor charts section.
ECALC-1331
> Ecalc 1331 update example to reflect that units are required

- docs/docs/changelog/next.md
- src/libecalc/core/models/compressor/base.py
- src/libecalc/core/models/compressor/train/base.py
- src/libecalc/core/models/compressor/train/variable_speed_compressor_train_common_shaft_multiple_streams_and_pressures.py
- src/libecalc/core/models/turbine.py
- src/libecalc/presentation/yaml/mappers/model.py
- src/libecalc/presentation/yaml/yaml_keywords.py
- src/libecalc/presentation/yaml/yaml_types/models/yaml_compressor_trains.py
- src/libecalc/presentation/yaml/yaml_types/models/yaml_compressor_with_turbine.py
- src/libecalc/presentation/yaml/yaml_types/models/yaml_turbine.py
- src/tests/libecalc/core/models/compressor_modelling/test_variable_speed_compressor_train_common_shaft.py
- src/tests/libecalc/core/models/test_turbine.py
ECALC-1361
`POWER_ADJUSTMENT_FACTOR` is not yet implemented for models. There are examples where users are applying the `POWERLOSSFACTOR` for calibration of equipment/models, in lack of other alternatives (the power loss factor is not intended for equipment calibration). In some cases this can give problems, e.g. for directly driven compressors (they don´t have any power loss). 
https://equinor-ecalc.atlassian.net/browse/ECALC-1361?atlOrigin=eyJpIjoiZTVhYWFkZWE2ZDEwNDg4ZmE1MGQyMTI4MmRjOGI4NzciLCJwIjoiaiJ9
> feat: add adjustment factor for models (new)

- src/libecalc/presentation/yaml/mappers/model.py
- src/libecalc/presentation/yaml/yaml_types/models/yaml_compressor_trains.py
Default pressure control was added to variable speed train, but forgotten for single speed and multiple streams.
> fix: make sure default pressure control is set for all trains

- src/ecalc_cli/io/output.py
- src/ecalc_neqsim_wrapper/thermo.py
- src/libecalc/fixtures/cases/all_energy_usage_models/conftest.py
- src/libecalc/fixtures/conftest.py
- src/libecalc/presentation/flow_diagram/fde_models.py
- src/tests/libecalc/core/conftest.py
- src/tests/libecalc/core/models/compressor_modelling/conftest.py
- src/tests/libecalc/dto/test_composition.py
Removing pydantic DeprecationWarnings
Only changed some deprecated methods for pydantic.
ECALC-1745
> Ecalc 1745 pydantic deprecationwarnings

- src/libecalc/presentation/json_result/mapper.py
When looping consumer results we won't get installations and assets,
as we are calculating them after based on the results of sub components.
> chore: remove unused code

- src/libecalc/core/models/compressor/train/simplified_train.py
- src/libecalc/core/models/results/compressor.py
- src/libecalc/expression/expression.py
- src/libecalc/fixtures/cases/ltp_export/installation_setup.py
- src/libecalc/presentation/flow_diagram/fde_models.py
- src/tests/libecalc/presentation/yaml/test_venting_emitter.py
This pull request is needed because the project should be ready for numpy 2 upgrade in the future for its own sake, and in case the Komodo environment will upgrade to numpy 2 eventually.
Note: Since the deprecation warnings are found by running the tests, the refactoring is already tested for.
Refactoring some code related to numpy 2 deprecation warnings.
Ecalc 1531
> Ecalc 1531 numpy2 ready

- .github/pull_request_template.md
- .github/workflows/docs-ci.yml
- .github/workflows/docs-publish.yml
- .github/workflows/examples-ci.yml
- .github/workflows/lib-ci.yml
- .github/workflows/pre-ci.yml
- .github/workflows/publish.yml
- Dockerfile
- README.md
- docs/docs/about/getting_started/cli/index.md
- docs/drafts/next.draft.md
- poetry.lock
- pyproject.toml
*    Drop Python 3.8,3.9 and 3.10 support (drop CICD testing)
*    Explicit Python 3.13 support (add CICD testing)
> Ecalc 1770 ecalc 9.0

- pyproject.toml
- src/libecalc/fixtures/cases/venting_emitters/venting_emitter_yaml.py
- src/tests/ecalc_cli/test_app.py
- test/README.md
- test/docker-compose.yml
To run STP/LTP tests in Docker since there are discrepancies between ARM and x86 for Python 3.11. Always runnign this in x86 in container avoids this problem. We are ok with teh differences, they are negligible.
> Run STP snapshots in docker container on x86 arch

- src/tests/libecalc/presentation/yaml/yaml_types/models/conftest.py
due to incorrect conflict resolving due to commit that was pushed with python 3.8 defaults while i was working on ruff 3.11 defaults.
> chore: refix additional python 3.11 ruff complaints

- src/libecalc/common/utils/rates.py
- src/libecalc/core/consumers/legacy_consumer/component.py
- src/libecalc/presentation/exporter/queries.py
- src/tests/libecalc/common/utils/test_rates.py
- src/tests/libecalc/core/consumers/test_legacy_consumer.py
Some clean up in rates.py
Renaming `reindex` to `fill_values_for_new_periods` (as that is what is actually done)
Removing reindex_periods/time_vector from Consumer class
> chore: clean up TimeSeriesRate and remove reindex from consumer

- .devcontainer/python/devcontainer.json
Just removed two testing related extensions from the devcontainer which are not needed since their functionality is now covered by the python extension.
ECALC-1622
> chore: remove extensions from devcontainer not needed

- pyproject.toml
- test/README.md
- test/docker-compose.yml
Need to run some tests marked dockersnapshot in docker container to make them pass. The snapshot update should also be run in docker container. New docker compose service will run all tests in docker container in one run.
In the future, e.g. when updating numpy to version >2, it seems that tests 
ECALC-1531
> Ecalc-1531 numpy2 ready

- src/libecalc/core/models/compressor/train/variable_speed_compressor_train_common_shaft_multiple_streams_and_pressures.py
- src/tests/libecalc/core/models/compressor_modelling/test_variable_speed_compressor_train_multiple_streams.py
The get max standard rate algorithm for a multiple streams and pressures compressor train does not work fully as intended. Changing to a brute force algorithm, instead of trying to be clever in searching along max speed curve and stone wall etc (old code over 400 lines, this one around 60-70).
This algorithm will of course be more computationally demanding.
Refs.
ECALC-416
> chore: alternative  algorithm for get max rate for streams

- docs/docs/about/migration_guides/v8.26_to_v9.0.md
- docs/docs/about/modelling/setup/models/compressor_modelling/compressor_models_types/simplified_variable_speed_compressor_train_model.md
- docs/docs/about/modelling/setup/models/compressor_modelling/compressor_models_types/single_speed_compressor_train_model.md
- docs/docs/about/modelling/setup/models/compressor_modelling/compressor_models_types/variable_speed_compressor_train_model.md
- docs/docs/about/modelling/setup/models/compressor_modelling/compressor_models_types/variable_speed_compressor_train_model_with_multiple_streams_and_pressures.md
- docs/docs/changelog/v9-0.md
- docs/src/css/custom.css
ECALC-1790
CONTROL_MARGIN and CONTROL_MARGIN_UNIT are required for all compressor trains except simplified trains. Generic charts are restricted to simplified trains. These are breaking changes and should be reflected in documentation and migration guide.
https://equinor-ecalc.atlassian.net/browse/ECALC-1790?atlOrigin=eyJpIjoiZDEyN2VkNGFhOTE2NDc0Mjg5MWY4ZjFhOTg0MzUwN2EiLCJwIjoiaiJ9
> docs: update docs and migration guide with new requirements for control margin and generic charts

- src/libecalc/core/models/chart/base.py
Control margin is now required to define for single speed and variable speed compressor charts, so it should no longer be labeled as experimental.
> chore: remove warning stating that control margin is experimental

- src/libecalc/presentation/yaml/yaml_types/components/legacy/yaml_electricity_consumer.py
- src/libecalc/presentation/yaml/yaml_types/components/legacy/yaml_fuel_consumer.py
- src/libecalc/testing/yaml_builder.py
ECALC-1813
Test data for ltp is currently created using data transfer objects (dtos) in installation_setup.
Yaml builders represent a more generic way of setting up input data for testing. Yaml builders should replace the dtos in th current ltp test installation setup. Missing builders (e.g. for generator sets etc.) should be created.
Tests will be added when replacing dtos with builders in ltp tests, in a separate pull request.
https://equinor-ecalc.atlassian.net/browse/ECALC-1813?atlOrigin=eyJpIjoiMjAyODY0MmFmMmU4NGU5MGJmNzc3NzRjYjE4NTcxYzciLCJwIjoiaiJ9
> chore: create new yaml builders for testing

- .github/workflows/docs-ci.yml
- .github/workflows/docs-publish.yml
- docs/README.md
- docs/docs/about/getting_started/yaml/ecalc_json_schema.json
- docs/docs/about/getting_started/yaml/index.md
- docs/docs/about/migration_guides/v7_to_v8.md
- src/ecalc_cli/commands/show.py
- src/ecalc_cli/io/output.py
- src/generate_docs.py
- src/generate_json_schema.py
* `ecalc show schema [--file my_file]` will write the current json schema for valid ecalc yaml to the file my_file. If no filename is provided, it will write to stdout
* fixed paths to cli reference that was incorrect, and updated it
* link to json schema from ecalc docs (will serve latest bleeding json schema from main)
> feat: get json schema for ecalc yaml in cli

- src/libecalc/presentation/yaml/domain/time_series_collections.py
- src/libecalc/presentation/yaml/model.py
When collecting the tokens from time series collection, we don't want to
raise an error since that would limit the information we get from
validation. Instead we want to collect the tokens we can, then validate
the model based on that context. The errors will still give information
about a missing resource, but also additional information, and file
context.
> fix: don't raise error when missing time series on token collection

- src/libecalc/common/time_utils.py
- src/libecalc/presentation/simple_result/simple.py
due to opposite check of what it was supposed to, ie. check that
we only include periods that are given in the common period vector,
but instead there was a check that the separate result had a
period that was not in the common period vector.
Resolves equinor/ecalc-internal#298
> fix: delta profile when 2 result sets have different periods

- .github/workflows/docs-ci.yml
- .github/workflows/docs-publish.yml
- .github/workflows/examples-ci.yml
- .github/workflows/lib-ci.yml
Poetry just released v2.0.0, which causes ci to break. Set it to v1.8.4 for now as that is the version we are currently using.
> chore: specify poetry version in ci

- src/libecalc/presentation/yaml/validation_errors.py
Update validation error to allow string or None. Avoid TypeScript errors when trying to assign to assign string | null to location.
> chore: update validation error to allow string or none

- docs/docs/about/modelling/workflow/generic_workflow.md
I don't have the sketches made previously, so some of the comments are hard to address. Tried to fix most things.
> docs: update generic workflow description in documentation

- src/libecalc/domain/infrastructure/emitters/venting_emitter.py
- src/libecalc/domain/infrastructure/energy_components/consumer_system/consumer_system_dto.py
- src/libecalc/domain/infrastructure/energy_components/electricity_consumer/electricity_consumer.py
- src/libecalc/domain/infrastructure/energy_components/fuel_consumer/fuel_consumer.py
- src/libecalc/domain/infrastructure/energy_components/generator_set/generator_set_dto.py
- tests/libecalc/integration/test_all_consumer_with_time_slots_models.py
This PR is part of a larger refactoring of results. It will not implement any functional changes, but is part of a preparation with the objective to allow individual components to be queried directly for their results, simplifying the retrieval process.
https://github.com/equinor/ecalc-internal/issues/505
> refactor: store results in fuel and electricity components

- src/ecalc_cli/commands/run.py
- src/ecalc_cli/commands/selftest.py
- src/ecalc_neqsim_wrapper/__init__.py
- src/ecalc_neqsim_wrapper/java_service.py
- src/ecalc_neqsim_wrapper/mappings.py
- src/ecalc_neqsim_wrapper/thermo.py
- tests/conftest.py
- tests/ecalc_neqsim_wrapper/conftest.py
- tests/ecalc_neqsim_wrapper/unit_tests/test_java_service.py
When starting a new java-process we also need to clear the NeqsimFluid cache, since the py4j/java-connection is stored within the cached objects (JavaObject from py4j).
> feat: manually control java process for neqsim

- src/libecalc/presentation/yaml/mappers/variables_mapper/variables_mapper.py
- src/libecalc/presentation/yaml/model.py
- tests/libecalc/input/mappers/variables_mapper/test_variables_mapper.py
Catch the error and convert it to an expected error.
Further improvement could be to evaluate variables when needed, but it
would still be nice if we could make sure we _can_ solve in
validating.
> fix: error message when variables are unsolvable

- src/libecalc/presentation/yaml/yaml_models/pyyaml_yaml_model.py
- src/libecalc/presentation/yaml/yaml_models/yaml_model.py
- src/libecalc/presentation/yaml/yaml_types/components/yaml_asset.py
- tests/libecalc/input/test_file_io.py
If specifying only a keyword without the data for an optional keyword in
the yaml we would not get a validation error. I.e. the json-schema did
not capture the error. In addition, the validation context setup did not
account for None in the data, expecting either unset or some data (not
None). This caused a type error since we then tried to use None as a
list.
Adding only `MODELS:` to the yaml would reproduce the error. Removing
`MODELS:` or adding an empty list `MODELS: []` would make it valid.
> fix: issue with empty optional keywords

- src/libecalc/domain/component_validation_error.py
- src/libecalc/domain/process/core/compressor/train/chart/types.py
- src/libecalc/domain/process/core/compressor/train/stage.py
- src/libecalc/domain/process/core/compressor/train/types.py
- src/libecalc/domain/process/core/tabulated.py
Part of libecalc refactoring and code improvements.
- Remove pydantic from: libecalc.domain.process.core (previously named models in main core folder)
- Remove mainly compressor related
- Update affected classes and methods
> chore: remove pydantic from domain process core compressor

- .github/workflows/publish.yml
v4.0.2 is deprecated, v4.2.0 contains important changes. https://github.com/actions/cache/releases/tag/v4.2.0
> ci: use latest v4 cache action

- src/ecalc_neqsim_wrapper/thermo.py
- src/libecalc/common/fluid.py
- src/libecalc/domain/process/core/stream/__init__.py
- src/libecalc/domain/process/core/stream/conditions.py
- src/libecalc/domain/process/core/stream/exceptions.py
- src/libecalc/domain/process/core/stream/fluid.py
- src/libecalc/domain/process/core/stream/fluid_factory.py
- src/libecalc/domain/process/core/stream/mixing.py
- src/libecalc/domain/process/core/stream/stream.py
- src/libecalc/domain/process/core/stream/thermo_adapters.py
- src/libecalc/domain/process/core/stream/thermo_constants.py
- tests/libecalc/common/test_fluid_common.py
- tests/libecalc/domain/core/stream/conftest.py
- tests/libecalc/domain/core/stream/test_conditions.py
- tests/libecalc/domain/core/stream/test_fluid.py
- tests/libecalc/domain/core/stream/test_fluid_factory.py
- tests/libecalc/domain/core/stream/test_mixing.py
- tests/libecalc/domain/core/stream/test_stream.py
- tests/libecalc/domain/core/stream/test_thermo_adapters.py
- tests/libecalc/domain/core/stream/test_thermo_constants.py
To create centralized domain entity around fluid and stream and to create a thermodynamic adapter for future modifications of thermodynamic engine or simplifications and optimizations related to thermodynamic calculations.
- Centralizes domain entities for fluid and stream processing by defining dedicated classes for process conditions, fluid, and stream.
- Implements the NeqSim thermodynamic adapter to encapsulate interactions with the NeqSim Java service, paving the way for future modifications/optimizations or changing thermo engine more easily.
- Introduces a simplified stream mixing strategy with molar balance with simplifications similar to the ones used earlier in the neqsim fluid mix method, but a little enhanced by assuming outlet set to lowest inlet pressure and a simplified …
> Create stream and fluid domain with thermodynamic adapter

- src/libecalc/domain/process/core/stream/stream.py
- tests/libecalc/domain/core/stream/test_stream.py
Fix fluid thermo getter error in Stream object
> fix: stream using old method of getting fluid thermo engine

- docs/drafts/next.draft.md
- src/libecalc/domain/process/core/compressor/train/variable_speed_compressor_train_common_shaft_multiple_streams_and_pressures.py
- tests/libecalc/core/models/compressor_modelling/test_variable_speed_compressor_train_multiple_streams.py
The check for power being above/below maximum power has for some reason not been implemented for multiple streams compressor trains. This PR adds this fix (in addition to a test to check that it works).
> fix: add check for maximum power in multiple streams compressor train

- src/libecalc/domain/component_validation_error.py
- src/libecalc/domain/infrastructure/energy_components/generator_set/generator_set_component.py
- src/libecalc/domain/infrastructure/energy_components/legacy_consumer/consumer_function/results.py
- src/libecalc/domain/infrastructure/energy_components/legacy_consumer/system/results.py
- src/libecalc/domain/infrastructure/energy_components/utils.py
Refs equinor/ecalc-internal#756
**Summary**
This pull request fixes a bug where `ModelValidationError.location` could be `None`, causing a type mismatch in the backend. The changes ensure that location is always non-None, improving validation consistency and preventing backend errors.
<hr></hr> 
**Changes**
- Updated `ModelValidationError` in libecalc/src/libecalc/domain/component_validation_error.py to ensure location cannot be None.
- Added location to errors that were previously missing it.
<hr></hr> 
**Type**
fix: Resolves a bug related to backend validation errors.
> fix: ensure location is non-None to resolve backend type mismatch

- src/libecalc/domain/component_validation_error.py
- src/libecalc/domain/infrastructure/energy_components/generator_set/__init__.py
- src/libecalc/domain/infrastructure/energy_components/generator_set/generator_set_component.py
- src/libecalc/domain/infrastructure/energy_components/generator_set/generator_set_model.py
- src/libecalc/domain/infrastructure/energy_components/generator_set/generator_set_validator.py
- src/libecalc/domain/process/generator_set/__init__.py
- src/libecalc/fixtures/cases/consumer_with_time_slots_models.py
- src/libecalc/presentation/yaml/domain/reference_service.py
- src/libecalc/presentation/yaml/mappers/energy_model_factory.py
- src/libecalc/presentation/yaml/mappers/facility_input.py
- src/libecalc/presentation/yaml/yaml_entities.py
- tests/libecalc/core/consumers/conftest.py
- tests/libecalc/core/models/test_generator_model.py
- tests/libecalc/dto/test_generator_set.py
- tests/libecalc/input/mappers/test_facility_input.py
This PR refactors the generator set-related classes to improve code organization and clarity
- **Moved** `GeneratorSetProcessUnit` and `GeneratorSetValidator` from domain.process.generator_set to domain.infrastructure.energy_components.generator_set to better reflect their domain and usage.
- **Renamed** `GeneratorSetProcessUnit` to `GeneratorSetModel` for a more accurate and descriptive class name.
- **Removed inheritance** from `ProcessUnit` in the new `GeneratorSetModel`, as it doesn´t handle streams but is mainly relevant in the energy domain.
- Updated imports and references throughout the codebase to reflect these changes.
No functional changes to the generator set logic are introduced.
> refactor generator set classes: move, rename and update inheritance

- src/libecalc/domain/infrastructure/energy_components/legacy_consumer/tabulated/tabular_consumer_function.py
- src/libecalc/domain/infrastructure/energy_components/legacy_consumer/tabulated/tabular_energy_function.py
- src/libecalc/presentation/yaml/mappers/consumer_function_mapper.py
- tests/libecalc/core/conftest.py
- tests/libecalc/core/consumers/conftest.py
- tests/libecalc/core/models/test_consumer_tabular_energy_function.py
This pull request is part 3 of a multi-step refactoring to improve the structure, maintainability, and clarity of the codebase for tabular energy functions related to legacy consumers. While the previous parts focused on reorganizing, renaming, and consolidating logic, this part is necessary to further decouple responsibilities and clarify the flow of tabular energy calculations. Specifically, this PR moves the responsibility for evaluating tabular energy variables out of `TabularEnergyFunction` and into `TabularConsumerFunction`, making the separation between core interpolation logic and consumer-specific evaluation more explicit. Splitting the work into several PRs ensures that each step remains manageable and reviewable.
- Refactors `TabularConsumerFunction` to directly construct and …
> refactor: tabular consumer function part 3

- src/libecalc/common/version.py
- tests/libecalc/common/test_version.py
Previously only versions on format X.Y.Z was allowed, all other version strings would be treated as version 0.0.0. Now vX.Y.Z is also allowed.
Refs: equinor/ecalc-internal#915
> chore: allow versionstrings with v prefix to be treated as version

- src/libecalc/domain/infrastructure/energy_components/legacy_consumer/consumer_function/direct_consumer_function.py
- src/libecalc/domain/infrastructure/energy_components/legacy_consumer/consumer_function/pump_consumer_function.py
- src/libecalc/domain/time_series_flow_rate.py
- src/libecalc/domain/time_series_power.py
- src/libecalc/presentation/yaml/domain/expression_time_series_flow_rate.py
- src/libecalc/presentation/yaml/domain/expression_time_series_power.py
- src/libecalc/presentation/yaml/mappers/consumer_function_mapper.py
- tests/libecalc/core/consumers/consumer_function/test_direct_expression_consumer_function.py
The current implementation of consumer functions uses generic expressions for power loss factors and period alignment, which limits flexibility and consistency when handling time series data.
This PR refactors the consumer function logic to use dedicated time series classes for power loss factors (`TimeSeriesPowerLossFactor`), flow rate, and power, including explicit period alignment via new get_periods() methods. It updates the mapping logic and tests to support these changes, ensuring clearer, more robust handling of time series data throughout the codebase.
Refs equinor/ecalc-internal#1001
> refactor: direct consumer function time series power loss factor

- src/libecalc/domain/infrastructure/energy_components/legacy_consumer/tabulated/tabular_consumer_function.py
- src/libecalc/domain/time_series_variable.py
- src/libecalc/presentation/yaml/domain/expression_time_series_variable.py
- src/libecalc/presentation/yaml/domain/time_series_expression.py
- src/libecalc/presentation/yaml/domain/time_series_mask.py
- src/libecalc/presentation/yaml/mappers/consumer_function_mapper.py
- tests/libecalc/core/conftest.py
- tests/libecalc/core/consumers/conftest.py
- tests/libecalc/core/models/test_consumer_tabular_energy_function.py
- tests/libecalc/domain/infrastructure/energy_components/legacy_consumer/test_tabular_consumer_function.py
- tests/libecalc/presentation/yaml/domain/test_time_series_mask.py
This PR is required to improve the handling and consistency of time series data in tabular consumer functions. 
- Refactors the tabular consumer function logic to use unified time series interfaces for variables and power loss factors.
- Introduces new abstractions (such as `TimeSeriesVariable` and `ExpressionTimeSeriesVariable`) to standardize how time series data is provided and evaluated.
- Updates the evaluation logic so that tabular consumer functions consistently handle rate conversion, conditional masking, and interpolation of tabular data.
- Cleans up legacy code, removing duplicated logic or interfaces.
- Updates related mappers, tests, and consumer factories to use the new interfaces.
Refs equinor/ecalc-internal#1001
> refactor: unify tabular consumer time series interfaces

- src/libecalc/presentation/yaml/domain/expression_time_series_flow_rate.py
- src/libecalc/presentation/yaml/domain/expression_time_series_power.py
- src/libecalc/presentation/yaml/mappers/consumer_function_mapper.py
- tests/libecalc/core/consumers/consumer_function/test_direct_expression_consumer_function.py
This PR is needed to simplify and improve the handling of conditional logic for time series expressions in the codebase. Previously, condition expressions were managed separately and added unnecessary complexity when mapping and evaluating time series data for flow rates and power. By refactoring how conditions are passed and evaluated, the code becomes easier to maintain, less error-prone, and more consistent.
- Removes the separate handling of condition_expression in several classes and mapping functions.
- Integrates the condition directly into the TimeSeriesExpression object via a new condition argument.
- Updates usage throughout the codebase, including constructors and mapper functions, to reflect this new structure.
- Refactors the implementation to use get_masked_values() instead …
> refactor: simplify condition handling in time series expressions

- release-please-config.json
since uv.lock files includes the current package as well, with the current version, we will also have to update uv.lock.
there is currently not support for this in release-please, and we will therefore have to add a "hack" to make sure the uv.lock file is updated on release
> ci: make release please correctly update uv.lock on new version

- .github/dependabot.yml
- .github/workflows/on-push-main-branch.yml
- .github/workflows/update-requirements.yml
Support for uv.lock is rather spotty.
Export uv requirements to requirements.txt format, push it to separate branch that can be scanned by dependabot.
> ci: workflow for freezing reqs to seperate branch

- src/libecalc/domain/process/compressor/core/factory.py
- src/libecalc/domain/process/compressor/core/train/simplified_train.py
- src/libecalc/domain/process/compressor/dto/train.py
- tests/libecalc/core/models/compressor_modelling/test_compressor_model_vs_unisim.py
- tests/libecalc/core/models/compressor_modelling/test_simplified_compressor_train.py
- tests/libecalc/dto/test_energy_model.py
The current design of `CompressorTrainSimplifiedKnownStages` relies on a Data Transfer Object (DTO) for initialization, which limits flexibility and makes testing more complex. This pull request improves modularity and testability by refactoring the class to use explicit arguments instead of a DTO.
- The PR refactors `CompressorTrainSimplifiedKnownStages` to accept direct constructor arguments.
- All usages—including factories, fixtures, and tests—are updated to use the new constructor.
- The dependency on `CompressorTrainSimplifiedWithKnownStages` DTO is removed.
> refactor: remove dto from simplified train with known stages

- src/libecalc/domain/process/compressor/core/factory.py
- src/libecalc/domain/process/compressor/core/train/single_speed_compressor_train_common_shaft.py
- tests/libecalc/core/models/compressor_modelling/conftest.py
- tests/libecalc/core/models/compressor_modelling/test_single_speed_compressor_train_common_shaft.py
The PR refactors how single speed compressor train models are constructed and tested. Previously, these models relied on a data transfer object (DTO) for initialization, which limited flexibility and clarity. This update aims to improve maintainability and make the codebase easier to test and extend, especially when adding new features or modifying model parameters.
- Refactors the `SingleSpeedCompressorTrainCommonShaft` class to accept explicit arguments instead of a DTO, enhancing clarity and flexibility.
- Updates the factory function and all relevant tests to use the new initialization pattern.
- Simplifies and unifies test fixtures, reducing duplication and making tests easier to configure with different parameters.
- Removes unused DTO properties and cleans up related code.
> refactor: remove dto from single speed compressor train

- src/libecalc/domain/process/compressor/core/factory.py
- src/libecalc/domain/process/compressor/core/train/base.py
- src/libecalc/domain/process/compressor/core/train/stage.py
- src/libecalc/domain/process/compressor/core/train/variable_speed_compressor_train_common_shaft_multiple_streams_and_pressures.py
- src/libecalc/domain/process/compressor/core/utils.py
- src/libecalc/domain/process/compressor/dto/stage.py
- src/libecalc/domain/process/compressor/dto/train.py
- src/libecalc/presentation/yaml/yaml_types/models/yaml_compressor_trains.py
- tests/libecalc/core/models/compressor_modelling/conftest.py
- tests/libecalc/core/models/compressor_modelling/test_compressor_with_turbine.py
- tests/libecalc/core/models/compressor_modelling/test_variable_speed_compressor_train_multiple_streams.py
- tests/libecalc/presentation/yaml/yaml_types/models/test_yaml_variable_speed_compressor_train_multiple_streams_and_pressures.py
Remove the use of DTOs in the compressor train code.
- Refactors the handling of compressor train stages and interstage pressure control by moving logic from DTO classes into the domain model.
- Updates the construction and validation of `VariableSpeedCompressorTrainCommonShaftMultipleStreamsAndPressures` to work directly with domain model stages, rather than DTOs.
- Moves validation of stage compatibility and interstage pressure control from DTOs to the domain model and YAML layer.
- Updates related tests and fixtures to use the new approach.
> refactor: remove dto from compressor train multiple streams and pressures

- src/libecalc/domain/process/compressor/core/factory.py
- src/libecalc/domain/process/compressor/core/train/single_speed_compressor_train_common_shaft.py
- src/libecalc/domain/process/compressor/dto/__init__.py
- src/libecalc/domain/process/compressor/dto/train.py
- src/libecalc/presentation/yaml/mappers/consumer_function_mapper.py
- tests/libecalc/core/models/compressor_modelling/conftest.py
- tests/libecalc/core/models/compressor_modelling/test_single_speed_compressor_train_common_shaft.py
- tests/libecalc/dto/test_energy_model.py
The PR removes the `SingleSpeedCompressorTrain` DTO and related code, simplifying the compressor train modeling by using the core implementation directly. This reduces duplication and potential sources of confusion or errors.
- Deletes the `SingleSpeedCompressorTrain` class from the DTO layer and its references throughout the codebase.
- Refactors factories, mappers, and tests to use SingleSpeedCompressorTrainCommonShaft directly.
- Moves validation logic for single speed compressor trains from the DTO layer to the core implementation.
- Updates related imports, object creation, and test fixtures accordingly.
> refactor: remove final dto single speed compressor train

- src/libecalc/domain/process/compressor/core/factory.py
- src/libecalc/domain/process/compressor/core/train/simplified_train.py
- src/libecalc/domain/process/compressor/dto/__init__.py
- src/libecalc/domain/process/compressor/dto/train.py
- src/libecalc/presentation/yaml/mappers/consumer_function_mapper.py
- tests/libecalc/core/models/compressor_modelling/test_compressor_model_vs_unisim.py
- tests/libecalc/core/models/compressor_modelling/test_simplified_compressor_train.py
- tests/libecalc/dto/test_energy_model.py
This PR simplifies the handling of simplified compressor train models by removing unused DTO classes and factory methods, and ensures mapping between DTOs and domain models happens at the correct layer.
- Removes the DTO classes `CompressorTrainSimplifiedWithKnownStages` and `CompressorTrainSimplifiedWithUnknownStages`.
- Removes corresponding factory methods and related imports.
- Refactors affected tests and code to use `CompressorTrainSimplifiedKnownStages` and CompressorTrainSimplifiedUnknownStages directly with domain types.
> refactor: remove final dto simplified train
